package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Adress extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdAddress=0;
    
    private String Line_1;
    
    private String Line_2;
    
    private String Line_3;
    
    private Integer IdCity;
    
    private String PostCode;
    
    private String AddressTypeCode;
    
    private City City;
    
    private RefAddressType RefAddressType;
    
    private ArrayOfCustomerAddress CustomerAddresses;
    
    private ArrayOfPartnerAddress PartnerAddresses;
    
    public Integer getIdAddress()
    {
        return this.IdAddress;
    }
    
    public void setIdAddress(Integer value)
    {
        this.IdAddress = value;     
    }
    
    public String getLine_1()
    {
        return this.Line_1;
    }
    
    public void setLine_1(String value)
    {
        this.Line_1 = value;     
    }
    
    public String getLine_2()
    {
        return this.Line_2;
    }
    
    public void setLine_2(String value)
    {
        this.Line_2 = value;     
    }
    
    public String getLine_3()
    {
        return this.Line_3;
    }
    
    public void setLine_3(String value)
    {
        this.Line_3 = value;     
    }
    
    public Integer getIdCity()
    {
        return this.IdCity;
    }
    
    public void setIdCity(Integer value)
    {
        this.IdCity = value;     
    }
    
    public String getPostCode()
    {
        return this.PostCode;
    }
    
    public void setPostCode(String value)
    {
        this.PostCode = value;     
    }
    
    public String getAddressTypeCode()
    {
        return this.AddressTypeCode;
    }
    
    public void setAddressTypeCode(String value)
    {
        this.AddressTypeCode = value;     
    }
    
    public City getCity()
    {
        return this.City;
    }
    
    public void setCity(City value)
    {
        this.City = value;     
    }
    
    public RefAddressType getRefAddressType()
    {
        return this.RefAddressType;
    }
    
    public void setRefAddressType(RefAddressType value)
    {
        this.RefAddressType = value;     
    }
    
    public ArrayOfCustomerAddress getCustomerAddresses()
    {
        return this.CustomerAddresses;
    }
    
    public void setCustomerAddresses(ArrayOfCustomerAddress value)
    {
        this.CustomerAddresses = value;     
    }
    
    public ArrayOfPartnerAddress getPartnerAddresses()
    {
        return this.PartnerAddresses;
    }
    
    public void setPartnerAddresses(ArrayOfPartnerAddress value)
    {
        this.PartnerAddresses = value;     
    }


    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdAddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdAddress = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdAddress = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Line_1"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Line_1 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Line_1 = (String)obj;
                }
                else{
                    this.Line_1 = "";
                }
            }
            return true;
        }
        if (info.name.equals("Line_2"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Line_2 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Line_2 = (String)obj;
                }
                else{
                    this.Line_2 = "";
                }
            }
            return true;
        }
        if (info.name.equals("Line_3"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Line_3 = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Line_3 = (String)obj;
                }
                else{
                    this.Line_3 = "";
                }
            }
            return true;
        }
        if (info.name.equals("IdCity"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCity = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCity = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PostCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PostCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.PostCode = (String)obj;
                }
                else{
                    this.PostCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("AddressTypeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AddressTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.AddressTypeCode = (String)obj;
                }
                else{
                    this.AddressTypeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("City"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.City = (City)__envelope.get(j,City.class,false);
            }
            return true;
        }
        if (info.name.equals("RefAddressType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefAddressType = (RefAddressType)__envelope.get(j,RefAddressType.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerAddresses"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerAddresses = (ArrayOfCustomerAddress)__envelope.get(j,ArrayOfCustomerAddress.class,false);
            }
            return true;
        }
        if (info.name.equals("PartnerAddresses"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PartnerAddresses = (ArrayOfPartnerAddress)__envelope.get(j,ArrayOfPartnerAddress.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }

    public Adress(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdAddress;
        }
        else if(propertyIndex==1)
        {
            return this.Line_1!=null?this.Line_1:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.Line_2!=null?this.Line_2:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Line_3!=null?this.Line_3:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.IdCity!=null?this.IdCity:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==5)
        {
            return this.PostCode!=null?this.PostCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.AddressTypeCode!=null?this.AddressTypeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.City!=null?this.City:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.RefAddressType!=null?this.RefAddressType:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==9)
        {
            return this.CustomerAddresses!=null?this.CustomerAddresses:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.PartnerAddresses!=null?this.PartnerAddresses:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdAddress";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Line_1";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Line_2";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Line_3";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCity";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PostCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AddressTypeCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = City.class;
            info.name = "City";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = RefAddressType.class;
            info.name = "RefAddressType";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerAddresses";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "PartnerAddresses";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
