package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BillDetail extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdBillDetail=0;
    
    private Integer IdBill=0;
    
    private String Description;
    
    private String Unit;
    
    private Integer Quantity;
    
    private Integer UnitPrice;
    
    private Integer Amount=0;
    
    private Bill Bill;
    
    public Integer getIdBillDetail()
    {
        return this.IdBillDetail;
    }
    
    public void setIdBillDetail(Integer value)
    {
        this.IdBillDetail = value;     
    }
    
    public Integer getIdBill()
    {
        return this.IdBill;
    }
    
    public void setIdBill(Integer value)
    {
        this.IdBill = value;     
    }
    
    public String getDescription()
    {
        return this.Description;
    }
    
    public void setDescription(String value)
    {
        this.Description = value;     
    }
    
    public String getUnit()
    {
        return this.Unit;
    }
    
    public void setUnit(String value)
    {
        this.Unit = value;     
    }
    
    public Integer getQuantity()
    {
        return this.Quantity;
    }
    
    public void setQuantity(Integer value)
    {
        this.Quantity = value;     
    }
    
    public Integer getUnitPrice()
    {
        return this.UnitPrice;
    }
    
    public void setUnitPrice(Integer value)
    {
        this.UnitPrice = value;     
    }
    
    public Integer getAmount()
    {
        return this.Amount;
    }
    
    public void setAmount(Integer value)
    {
        this.Amount = value;     
    }
    
    public Bill getBill()
    {
        return this.Bill;
    }
    
    public void setBill(Bill value)
    {
        this.Bill = value;     
    }


    public BillDetail(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdBillDetail"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdBillDetail = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdBillDetail = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdBill"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdBill = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdBill = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Description"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Description = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Description = (String)obj;
                }
                else{
                    this.Description = "";
                }
            }
            return true;
        }
        if (info.name.equals("Unit"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Unit = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Unit = (String)obj;
                }
                else{
                    this.Unit = "";
                }
            }
            return true;
        }
        if (info.name.equals("Quantity"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Quantity = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Quantity = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("UnitPrice"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.UnitPrice = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.UnitPrice = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Amount"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Amount = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Amount = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Bill"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Bill = (Bill)__envelope.get(j,Bill.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdBillDetail;
        }
        else if(propertyIndex==1)
        {
            return this.IdBill;
        }
        else if(propertyIndex==2)
        {
            return this.Description!=null?this.Description:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Unit!=null?this.Unit:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.Quantity!=null?this.Quantity:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==5)
        {
            return this.UnitPrice!=null?this.UnitPrice:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==6)
        {
            return this.Amount;
        }
        else if(propertyIndex==7)
        {
            return this.Bill!=null?this.Bill:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdBillDetail";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdBill";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Description";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Unit";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Quantity";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "UnitPrice";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Amount";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = Bill.class;
            info.name = "Bill";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
