package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BillPayment extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdBillPayment=0;
    
    private Integer IdBill=0;
    
    private String DatePaid;
    //private java.util.Date DatePaid;

    private Integer PaidAmount=0;
    
    private Boolean LastPayment=false;
    
    private Integer Fees;
    
    private Bill Bill;
    
    public Integer getIdBillPayment()
    {
        return this.IdBillPayment;
    }
    
    public void setIdBillPayment(Integer value)
    {
        this.IdBillPayment = value;     
    }
    
    public Integer getIdBill()
    {
        return this.IdBill;
    }
    
    public void setIdBill(Integer value)
    {
        this.IdBill = value;     
    }
    
//    public java.util.Date getDatePaid()
//    {
//        return this.DatePaid;
//    }
//
//    public void setDatePaid(java.util.Date value)
//    {
//        this.DatePaid = value;
//    }

    public String getDatePaid()
    {
        return this.DatePaid;
    }

    public void setDatePaid(String value)
    {
        this.DatePaid = value;
    }
    
    public Integer getPaidAmount()
    {
        return this.PaidAmount;
    }
    
    public void setPaidAmount(Integer value)
    {
        this.PaidAmount = value;     
    }
    
    public Boolean getLastPayment()
    {
        return this.LastPayment;
    }
    
    public void setLastPayment(Boolean value)
    {
        this.LastPayment = value;     
    }
    
    public Integer getFees()
    {
        return this.Fees;
    }
    
    public void setFees(Integer value)
    {
        this.Fees = value;     
    }
    
    public Bill getBill()
    {
        return this.Bill;
    }
    
    public void setBill(Bill value)
    {
        this.Bill = value;     
    }


    public BillPayment(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdBillPayment"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdBillPayment = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdBillPayment = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdBill"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdBill = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdBill = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DatePaid"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DatePaid = j.toString();
                        //this.DatePaid = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.DatePaid = (String)obj;
                    //this.DatePaid = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PaidAmount"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PaidAmount = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.PaidAmount = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LastPayment"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LastPayment = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.LastPayment = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Fees"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Fees = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Fees = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Bill"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Bill = (Bill)__envelope.get(j,Bill.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdBillPayment;
        }
        else if(propertyIndex==1)
        {
            return this.IdBill;
        }
        else if(propertyIndex==2)
        {
            return this.DatePaid!=null?this.DatePaid:SoapPrimitive.NullSkip;
            //return this.DatePaid!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.DatePaid):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.PaidAmount;
        }
        else if(propertyIndex==4)
        {
            return this.LastPayment;
        }
        else if(propertyIndex==5)
        {
            return this.Fees!=null?this.Fees:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==6)
        {
            return this.Bill!=null?this.Bill:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 7;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdBillPayment";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdBill";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DatePaid";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "PaidAmount";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "LastPayment";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Fees";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = Bill.class;
            info.name = "Bill";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
