package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Bill extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdBill=0;
    
    private Integer IdIssuingCustomer=0;
    
    private Integer IdPayingCustomer=0;
    
    private String CodeRefBillType;
    
    private String CodeRefBillStatus;
    
    private String DateIssued;
    //private java.util.Date DateIssued;

    private Integer TotalBillAmount=0;
    
    private Integer LeftToPay=0;
    
    private Boolean AllowPartialPayment=false;
    
    private java.util.Date DateCreation;
    
    private RefBillStatu RefBillStatu;
    
    private ArrayOfBillDetail BillDetails;
    
    private ArrayOfBillPayment BillPayments;
    
    private RefBillType RefBillType;
    
    private Customer Customer;
    
    private Customer Customer1;
    
    public Integer getIdBill()
    {
        return this.IdBill;
    }
    
    public void setIdBill(Integer value)
    {
        this.IdBill = value;     
    }
    
    public Integer getIdIssuingCustomer()
    {
        return this.IdIssuingCustomer;
    }
    
    public void setIdIssuingCustomer(Integer value)
    {
        this.IdIssuingCustomer = value;     
    }
    
    public Integer getIdPayingCustomer()
    {
        return this.IdPayingCustomer;
    }
    
    public void setIdPayingCustomer(Integer value)
    {
        this.IdPayingCustomer = value;     
    }
    
    public String getCodeRefBillType()
    {
        return this.CodeRefBillType;
    }
    
    public void setCodeRefBillType(String value)
    {
        this.CodeRefBillType = value;     
    }
    
    public String getCodeRefBillStatus()
    {
        return this.CodeRefBillStatus;
    }
    
    public void setCodeRefBillStatus(String value)
    {
        this.CodeRefBillStatus = value;     
    }
    
//    public java.util.Date getDateIssued()
//    {
//        return this.DateIssued;
//    }
//
//    public void setDateIssued(java.util.Date value)
//    {
//        this.DateIssued = value;
//    }

    public String getDateIssued()
    {
        return this.DateIssued;
    }

    public void setDateIssued(String value)
    {
        this.DateIssued = value;
    }
    
    public Integer getTotalBillAmount()
    {
        return this.TotalBillAmount;
    }
    
    public void setTotalBillAmount(Integer value)
    {
        this.TotalBillAmount = value;     
    }
    
    public Integer getLeftToPay()
    {
        return this.LeftToPay;
    }
    
    public void setLeftToPay(Integer value)
    {
        this.LeftToPay = value;     
    }
    
    public Boolean getAllowPartialPayment()
    {
        return this.AllowPartialPayment;
    }
    
    public void setAllowPartialPayment(Boolean value)
    {
        this.AllowPartialPayment = value;     
    }
    
    public java.util.Date getDateCreation()
    {
        return this.DateCreation;
    }
    
    public void setDateCreation(java.util.Date value)
    {
        this.DateCreation = value;     
    }
    
    public RefBillStatu getRefBillStatu()
    {
        return this.RefBillStatu;
    }
    
    public void setRefBillStatu(RefBillStatu value)
    {
        this.RefBillStatu = value;     
    }
    
    public ArrayOfBillDetail getBillDetails()
    {
        return this.BillDetails;
    }
    
    public void setBillDetails(ArrayOfBillDetail value)
    {
        this.BillDetails = value;     
    }
    
    public ArrayOfBillPayment getBillPayments()
    {
        return this.BillPayments;
    }
    
    public void setBillPayments(ArrayOfBillPayment value)
    {
        this.BillPayments = value;     
    }
    
    public RefBillType getRefBillType()
    {
        return this.RefBillType;
    }
    
    public void setRefBillType(RefBillType value)
    {
        this.RefBillType = value;     
    }
    
    public Customer getCustomer()
    {
        return this.Customer;
    }
    
    public void setCustomer(Customer value)
    {
        this.Customer = value;     
    }
    
    public Customer getCustomer1()
    {
        return this.Customer1;
    }
    
    public void setCustomer1(Customer value)
    {
        this.Customer1 = value;     
    }


    public Bill(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdBill"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdBill = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdBill = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdIssuingCustomer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdIssuingCustomer = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdIssuingCustomer = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdPayingCustomer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdPayingCustomer = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdPayingCustomer = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CodeRefBillType"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodeRefBillType = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodeRefBillType = (String)obj;
                }
                else{
                    this.CodeRefBillType = "";
                }
            }
            return true;
        }
        if (info.name.equals("CodeRefBillStatus"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CodeRefBillStatus = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CodeRefBillStatus = (String)obj;
                }
                else{
                    this.CodeRefBillStatus = "";
                }
            }
            return true;
        }
        if (info.name.equals("DateIssued"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateIssued = j.toString();
                        //this.DateIssued = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.DateIssued = (String)obj;
                    //this.DateIssued = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TotalBillAmount"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TotalBillAmount = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.TotalBillAmount = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LeftToPay"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LeftToPay = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.LeftToPay = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AllowPartialPayment"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.AllowPartialPayment = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.AllowPartialPayment = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DateCreation"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateCreation = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof java.util.Date){
                    this.DateCreation = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("RefBillStatu"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefBillStatu = (RefBillStatu)__envelope.get(j,RefBillStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("BillDetails"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BillDetails = (ArrayOfBillDetail)__envelope.get(j,ArrayOfBillDetail.class,false);
            }
            return true;
        }
        if (info.name.equals("BillPayments"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.BillPayments = (ArrayOfBillPayment)__envelope.get(j,ArrayOfBillPayment.class,false);
            }
            return true;
        }
        if (info.name.equals("RefBillType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefBillType = (RefBillType)__envelope.get(j,RefBillType.class,false);
            }
            return true;
        }
        if (info.name.equals("Customer"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Customer = (Customer)__envelope.get(j,Customer.class,false);
            }
            return true;
        }
        if (info.name.equals("Customer1"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Customer1 = (Customer)__envelope.get(j,Customer.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }



    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdBill;
        }
        else if(propertyIndex==1)
        {
            return this.IdIssuingCustomer;
        }
        else if(propertyIndex==2)
        {
            return this.IdPayingCustomer;
        }
        else if(propertyIndex==3)
        {
            return this.CodeRefBillType!=null?this.CodeRefBillType:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.CodeRefBillStatus!=null?this.CodeRefBillStatus:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.DateIssued!=null?this.DateIssued:SoapPrimitive.NullSkip;
            //return this.DateIssued!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.DateIssued):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.TotalBillAmount;
        }
        else if(propertyIndex==7)
        {
            return this.LeftToPay;
        }
        else if(propertyIndex==8)
        {
            return this.AllowPartialPayment;
        }
        else if(propertyIndex==9)
        {
            return this.DateCreation!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.DateCreation):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.RefBillStatu!=null?this.RefBillStatu:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==11)
        {
            return this.BillDetails!=null?this.BillDetails:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==12)
        {
            return this.BillPayments!=null?this.BillPayments:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==13)
        {
            return this.RefBillType!=null?this.RefBillType:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==14)
        {
            return this.Customer!=null?this.Customer:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==15)
        {
            return this.Customer1!=null?this.Customer1:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 16;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdBill";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdIssuingCustomer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdPayingCustomer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodeRefBillType";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CodeRefBillStatus";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateIssued";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TotalBillAmount";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "LeftToPay";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "AllowPartialPayment";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateCreation";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = RefBillStatu.class;
            info.name = "RefBillStatu";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "BillDetails";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "BillPayments";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==13)
        {
            info.type = RefBillType.class;
            info.name = "RefBillType";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==14)
        {
            info.type = Customer.class;
            info.name = "Customer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==15)
        {
            info.type = Customer.class;
            info.name = "Customer1";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
