package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class CustomerLogin implements KvmSerializable {
	
	private int idCustomer;
	private String number;
	private boolean numberVerified;
	private String emailAddress;
	private boolean emailAddressVerified;
	private String pwdSalt;
	private String pwd;
	private String recoveryToken;
	private String recoveryTokenExpiryDate;
	private String loginStatusCode;
	private Customer customer;
	private RefLoginStatu refLoginStatu;
	
	public CustomerLogin() {
	}
	
	public CustomerLogin(SoapObject soapObject) {
		if (soapObject == null)
			return;
		if (soapObject.hasProperty("IdCustomer")) {
			Object obj = soapObject.getProperty("IdCustomer");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setIdCustomer(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setIdCustomer((Integer) obj);
			}
		}
		if (soapObject.hasProperty("Number")) {
			Object obj = soapObject.getProperty("Number");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setNumber(j.toString());
			} else if (obj != null && obj instanceof String) {
				setNumber((String) obj);
			}
		}
		if (soapObject.hasProperty("NumberVerified")) {
			Object obj = soapObject.getProperty("NumberVerified");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setNumberVerified(Boolean.parseBoolean(j.toString()));
			} else if (obj != null && obj instanceof Boolean) {
				setNumberVerified((Boolean) obj);
			}
		}
		if (soapObject.hasProperty("EmailAddress")) {
			Object obj = soapObject.getProperty("EmailAddress");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setEmailAddress(j.toString());
			} else if (obj != null && obj instanceof String) {
				setEmailAddress((String) obj);
			}
		}
		if (soapObject.hasProperty("EmailAddressVerified")) {
			Object obj = soapObject.getProperty("EmailAddressVerified");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setEmailAddressVerified(Boolean.parseBoolean(j.toString()));
			} else if (obj != null && obj instanceof Boolean) {
				setEmailAddressVerified((Boolean) obj);
			}
		}
		if (soapObject.hasProperty("PwdSalt")) {
			Object obj = soapObject.getProperty("PwdSalt");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setPwdSalt(j.toString());
			} else if (obj != null && obj instanceof String) {
				setPwdSalt((String) obj);
			}
		}
		if (soapObject.hasProperty("Pwd")) {
			Object obj = soapObject.getProperty("Pwd");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setPwd(j.toString());
			} else if (obj != null && obj instanceof String) {
				setPwd((String) obj);
			}
		}
		if (soapObject.hasProperty("RecoveryToken")) {
			Object obj = soapObject.getProperty("RecoveryToken");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setRecoveryToken(j.toString());
			} else if (obj != null && obj instanceof String) {
				setRecoveryToken((String) obj);
			}
		}
		if (soapObject.hasProperty("RecoveryTokenExpiryDate")) {
			Object obj = soapObject.getProperty("RecoveryTokenExpiryDate");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setRecoveryTokenExpiryDate(j.toString());
			} else if (obj != null && obj instanceof String) {
				setRecoveryTokenExpiryDate((String) obj);
			}
		}
		if (soapObject.hasProperty("LoginStatusCode")) {
			Object obj = soapObject.getProperty("LoginStatusCode");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setLoginStatusCode(j.toString());
			} else if (obj != null && obj instanceof String) {
				setLoginStatusCode((String) obj);
			}
		}
		if (soapObject.hasProperty("Customer")) {
			SoapObject j = (SoapObject) soapObject.getProperty("Customer");
			setCustomer(new Customer(j));
			
		}
		if (soapObject.hasProperty("RefLoginStatu")) {
			SoapObject j = (SoapObject) soapObject.getProperty("RefLoginStatu");
			setRefLoginStatu(new RefLoginStatu(j));
			
		}
	}
	
	@Override
	public Object getProperty(int arg0) {
		switch (arg0) {
			case 0:
				return getIdCustomer();
			case 1:
				return getNumber();
			case 2:
				return isNumberVerified();
			case 3:
				return getEmailAddress();
			case 4:
				return isEmailAddressVerified();
			case 5:
				return getPwdSalt();
			case 6:
				return getPwd();
			case 7:
				return getRecoveryToken();
			case 8:
				return getRecoveryTokenExpiryDate();
			case 9:
				return getLoginStatusCode();
			case 10:
				return getCustomer();
			case 11:
				return getRefLoginStatu();
		}
		return null;
	}
	
	@Override
	public int getPropertyCount() {
		return 12;
	}
	
	@Override
	public void setProperty(int arg0, Object arg1) {
	}
	
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		switch (index) {
			case 0:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "IdCustomer";
				break;
			case 1:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "Number";
				break;
			case 2:
				info.type = PropertyInfo.BOOLEAN_CLASS;
				info.name = "NumberVerified";
				break;
			case 3:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "EmailAddress";
				break;
			case 4:
				info.type = PropertyInfo.BOOLEAN_CLASS;
				info.name = "EmailAddressVerified";
				break;
			case 5:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "PwdSalt";
				break;
			case 6:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "Pwd";
				break;
			case 7:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "RecoveryToken";
				break;
			case 8:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "RecoveryTokenExpiryDate";
				break;
			case 9:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "LoginStatusCode";
				break;
			case 10:
				info.type = Customer.class;
				info.name = "Customer";
				break;
			case 11:
				info.type = RefLoginStatu.class;
				info.name = "RefLoginStatu";
				break;
		}
	}
	
	public int getIdCustomer() {
		return idCustomer;
	}
	
	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}
	
	public String getNumber() {
		return number;
	}
	
	public void setNumber(String number) {
		this.number = number;
	}
	
	public boolean isNumberVerified() {
		return numberVerified;
	}
	
	public void setNumberVerified(boolean numberVerified) {
		this.numberVerified = numberVerified;
	}
	
	public String getEmailAddress() {
		return emailAddress;
	}
	
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	
	public boolean isEmailAddressVerified() {
		return emailAddressVerified;
	}
	
	public void setEmailAddressVerified(boolean emailAddressVerified) {
		this.emailAddressVerified = emailAddressVerified;
	}
	
	public String getPwdSalt() {
		return pwdSalt;
	}
	
	public void setPwdSalt(String pwdSalt) {
		this.pwdSalt = pwdSalt;
	}
	
	public String getPwd() {
		return pwd;
	}
	
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public String getRecoveryToken() {
		return recoveryToken;
	}
	
	public void setRecoveryToken(String recoveryToken) {
		this.recoveryToken = recoveryToken;
	}
	
	public String getRecoveryTokenExpiryDate() {
		return recoveryTokenExpiryDate;
	}
	
	public void setRecoveryTokenExpiryDate(String recoveryTokenExpiryDate) {
		this.recoveryTokenExpiryDate = recoveryTokenExpiryDate;
	}
	
	public String getLoginStatusCode() {
		return loginStatusCode;
	}
	
	public void setLoginStatusCode(String loginStatusCode) {
		this.loginStatusCode = loginStatusCode;
	}
	
	public Customer getCustomer() {
		return customer;
	}
	
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	public RefLoginStatu getRefLoginStatu() {
		return refLoginStatu;
	}
	
	public void setRefLoginStatu(RefLoginStatu refLoginStatu) {
		this.refLoginStatu = refLoginStatu;
	}
	
	//    @Override
	public String getInnerText() {
		return null;
	}
	
	//    @Override
	public void setInnerText(String s) {
	}
}
