package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class Customer extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdCustomer=0;
    
    private String CustomerTypeCode;
    
    private String CurrencyCode;
    
    private Integer Balance=0;
    
    private String DateCreated;
    //private java.util.Date DateCreated;

    private Integer IdRegistration;
    
    private Integer BalanceUnavailable=0;
    
    private String EneoContractNo;
    
    private Integer EneoPercentage;
    
    private Integer TopUpPercentage;
    
    private Integer GravityId;
    
    private String GravityCode;
    
    private Integer GravityPercentage;
    
    private ArrayOfAccountOperationRequest AccountOperationRequests;
    
    private ArrayOfActivation Activations;
    
    private ArrayOfBill IssuedBills;
    
    private ArrayOfBill PayedBills;
    
    private Business Business;
    
    private Currency Currency;
    
    private Registration Registration;
    
    private RefCustomerType RefCustomerType;
    
    private ArrayOfMobileDevice MobileDevices;
    
    private ArrayOfCustomerAddress CustomerAddresses;
    
    private ArrayOfCustomerBalanceHistory CustomerBalanceHistories;
    
    private ArrayOfCustomerGroup CustomerGroups;
    
    private CustomerImage CustomerImage;
    
    private CustomerLogin CustomerLogin;
    
    private ArrayOfCustomerTag CustomerTags;
    
    private ArrayOfEneoBillPayment EneoBillPayments;
    
    private ArrayOfExternalAccount ExternalAccounts;
    
    private ArrayOfKoloNotification KoloNotifications;
    
    public Partner Partner;
    
    public Person Person;
    
    private ArrayOfRecurringContribution RecurringContributions;
    
    private ArrayOfTopUp TopUps;
    
    private ArrayOfTransferGravity TransferGravities;
    
    private ArrayOfTransfert2CashDetail Transfert2CashDetails;
    
    private ArrayOfTransfertE2e TransfertE2e;
    
    private ArrayOfTransfertGroup TransfertGroups;
    
    private ArrayOfTransfertGroupScheduled TransfertGroupScheduleds;
    
    private ArrayOfTransfertP2p ReceivedTransfertP2p;
    
    private ArrayOfTransfertP2p SentTransfertP2p;
    
    private ArrayOfTransfertScheduled ReceivedTransfertScheduleds;
    
    private ArrayOfTransfertScheduled SentTransfertScheduleds;
    
    private ArrayOfCustomerGroup CustomerGroups1;
    
    public Integer getIdCustomer()
    {
        return this.IdCustomer;
    }
    
    public void setIdCustomer(Integer value)
    {
        this.IdCustomer = value;     
    }
    
    public String getCustomerTypeCode()
    {
        return this.CustomerTypeCode;
    }
    
    public void setCustomerTypeCode(String value)
    {
        this.CustomerTypeCode = value;     
    }
    
    public String getCurrencyCode()
    {
        return this.CurrencyCode;
    }
    
    public void setCurrencyCode(String value)
    {
        this.CurrencyCode = value;     
    }
    
    public Integer getBalance()
    {
        return this.Balance;
    }
    
    public void setBalance(Integer value)
    {
        this.Balance = value;     
    }
    
//    public java.util.Date getDateCreated()
//    {
//        return this.DateCreated;
//    }
//
//    public void setDateCreated(java.util.Date value)
//    {
//        this.DateCreated = value;
//    }

    public String getDateCreated()
    {
        return this.DateCreated;
    }

    public void setDateCreated(String value)
    {
        this.DateCreated = value;
    }
    
    public Integer getIdRegistration()
    {
        return this.IdRegistration;
    }
    
    public void setIdRegistration(Integer value)
    {
        this.IdRegistration = value;     
    }
    
    public Integer getBalanceUnavailable()
    {
        return this.BalanceUnavailable;
    }
    
    public void setBalanceUnavailable(Integer value)
    {
        this.BalanceUnavailable = value;     
    }
    
    public String getEneoContractNo()
    {
        return this.EneoContractNo;
    }
    
    public void setEneoContractNo(String value)
    {
        this.EneoContractNo = value;     
    }
    
    public Integer getEneoPercentage()
    {
        return this.EneoPercentage;
    }
    
    public void setEneoPercentage(Integer value)
    {
        this.EneoPercentage = value;     
    }
    
    public Integer getTopUpPercentage()
    {
        return this.TopUpPercentage;
    }
    
    public void setTopUpPercentage(Integer value)
    {
        this.TopUpPercentage = value;     
    }
    
    public Integer getGravityId()
    {
        return this.GravityId;
    }
    
    public void setGravityId(Integer value)
    {
        this.GravityId = value;     
    }
    
    public String getGravityCode()
    {
        return this.GravityCode;
    }
    
    public void setGravityCode(String value)
    {
        this.GravityCode = value;     
    }
    
    public Integer getGravityPercentage()
    {
        return this.GravityPercentage;
    }
    
    public void setGravityPercentage(Integer value)
    {
        this.GravityPercentage = value;     
    }
    
    public ArrayOfAccountOperationRequest getAccountOperationRequests()
    {
        return this.AccountOperationRequests;
    }
    
    public void setAccountOperationRequests(ArrayOfAccountOperationRequest value)
    {
        this.AccountOperationRequests = value;     
    }
    
    public ArrayOfActivation getActivations()
    {
        return this.Activations;
    }
    
    public void setActivations(ArrayOfActivation value)
    {
        this.Activations = value;     
    }
    
    public ArrayOfBill getIssuedBills()
    {
        return this.IssuedBills;
    }
    
    public void setIssuedBills(ArrayOfBill value)
    {
        this.IssuedBills = value;     
    }
    
    public ArrayOfBill getPayedBills()
    {
        return this.PayedBills;
    }
    
    public void setPayedBills(ArrayOfBill value)
    {
        this.PayedBills = value;     
    }
    
    public Business getBusiness()
    {
        return this.Business;
    }
    
    public void setBusiness(Business value)
    {
        this.Business = value;     
    }
    
    public Currency getCurrency()
    {
        return this.Currency;
    }
    
    public void setCurrency(Currency value)
    {
        this.Currency = value;     
    }
    
    public Registration getRegistration()
    {
        return this.Registration;
    }
    
    public void setRegistration(Registration value)
    {
        this.Registration = value;     
    }
    
    public RefCustomerType getRefCustomerType()
    {
        return this.RefCustomerType;
    }
    
    public void setRefCustomerType(RefCustomerType value)
    {
        this.RefCustomerType = value;     
    }
    
    public ArrayOfMobileDevice getMobileDevices()
    {
        return this.MobileDevices;
    }
    
    public void setMobileDevices(ArrayOfMobileDevice value)
    {
        this.MobileDevices = value;     
    }
    
    public ArrayOfCustomerAddress getCustomerAddresses()
    {
        return this.CustomerAddresses;
    }
    
    public void setCustomerAddresses(ArrayOfCustomerAddress value)
    {
        this.CustomerAddresses = value;     
    }
    
    public ArrayOfCustomerBalanceHistory getCustomerBalanceHistories()
    {
        return this.CustomerBalanceHistories;
    }
    
    public void setCustomerBalanceHistories(ArrayOfCustomerBalanceHistory value)
    {
        this.CustomerBalanceHistories = value;     
    }
    
    public ArrayOfCustomerGroup getCustomerGroups()
    {
        return this.CustomerGroups;
    }
    
    public void setCustomerGroups(ArrayOfCustomerGroup value)
    {
        this.CustomerGroups = value;     
    }
    
    public CustomerImage getCustomerImage()
    {
        return this.CustomerImage;
    }
    
    public void setCustomerImage(CustomerImage value)
    {
        this.CustomerImage = value;     
    }
    
    public CustomerLogin getCustomerLogin()
    {
        return this.CustomerLogin;
    }
    
    public void setCustomerLogin(CustomerLogin value)
    {
        this.CustomerLogin = value;     
    }
    
    public ArrayOfCustomerTag getCustomerTags()
    {
        return this.CustomerTags;
    }
    
    public void setCustomerTags(ArrayOfCustomerTag value)
    {
        this.CustomerTags = value;     
    }
    
    public ArrayOfEneoBillPayment getEneoBillPayments()
    {
        return this.EneoBillPayments;
    }
    
    public void setEneoBillPayments(ArrayOfEneoBillPayment value)
    {
        this.EneoBillPayments = value;     
    }
    
    public ArrayOfExternalAccount getExternalAccounts()
    {
        return this.ExternalAccounts;
    }
    
    public void setExternalAccounts(ArrayOfExternalAccount value)
    {
        this.ExternalAccounts = value;     
    }
    
    public ArrayOfKoloNotification getKoloNotifications()
    {
        return this.KoloNotifications;
    }
    
    public void setKoloNotifications(ArrayOfKoloNotification value)
    {
        this.KoloNotifications = value;     
    }
    
    public Partner getPartner()
    {
        return this.Partner;
    }
    
    public void setPartner(Partner value)
    {
        this.Partner = value;     
    }
    
    public Person getPerson()
    {
        return this.Person;
    }
    
    public void setPerson(Person value)
    {
        this.Person = value;     
    }
    
    public ArrayOfRecurringContribution getRecurringContributions()
    {
        return this.RecurringContributions;
    }
    
    public void setRecurringContributions(ArrayOfRecurringContribution value)
    {
        this.RecurringContributions = value;     
    }
    
    public ArrayOfTopUp getTopUps()
    {
        return this.TopUps;
    }
    
    public void setTopUps(ArrayOfTopUp value)
    {
        this.TopUps = value;     
    }
    
    public ArrayOfTransferGravity getTransferGravities()
    {
        return this.TransferGravities;
    }
    
    public void setTransferGravities(ArrayOfTransferGravity value)
    {
        this.TransferGravities = value;     
    }
    
    public ArrayOfTransfert2CashDetail getTransfert2CashDetails()
    {
        return this.Transfert2CashDetails;
    }
    
    public void setTransfert2CashDetails(ArrayOfTransfert2CashDetail value)
    {
        this.Transfert2CashDetails = value;     
    }
    
    public ArrayOfTransfertE2e getTransfertE2e()
    {
        return this.TransfertE2e;
    }
    
    public void setTransfertE2e(ArrayOfTransfertE2e value)
    {
        this.TransfertE2e = value;     
    }
    
    public ArrayOfTransfertGroup getTransfertGroups()
    {
        return this.TransfertGroups;
    }
    
    public void setTransfertGroups(ArrayOfTransfertGroup value)
    {
        this.TransfertGroups = value;     
    }
    
    public ArrayOfTransfertGroupScheduled getTransfertGroupScheduleds()
    {
        return this.TransfertGroupScheduleds;
    }
    
    public void setTransfertGroupScheduleds(ArrayOfTransfertGroupScheduled value)
    {
        this.TransfertGroupScheduleds = value;     
    }
    
    public ArrayOfTransfertP2p getReceivedTransfertP2p()
    {
        return this.ReceivedTransfertP2p;
    }
    
    public void setReceivedTransfertP2p(ArrayOfTransfertP2p value)
    {
        this.ReceivedTransfertP2p = value;     
    }
    
    public ArrayOfTransfertP2p getSentTransfertP2p()
    {
        return this.SentTransfertP2p;
    }
    
    public void setSentTransfertP2p(ArrayOfTransfertP2p value)
    {
        this.SentTransfertP2p = value;     
    }
    
    public ArrayOfTransfertScheduled getReceivedTransfertScheduleds()
    {
        return this.ReceivedTransfertScheduleds;
    }
    
    public void setReceivedTransfertScheduleds(ArrayOfTransfertScheduled value)
    {
        this.ReceivedTransfertScheduleds = value;     
    }
    
    public ArrayOfTransfertScheduled getSentTransfertScheduleds()
    {
        return this.SentTransfertScheduleds;
    }
    
    public void setSentTransfertScheduleds(ArrayOfTransfertScheduled value)
    {
        this.SentTransfertScheduleds = value;     
    }
    
    public ArrayOfCustomerGroup getCustomerGroups1()
    {
        return this.CustomerGroups1;
    }
    
    public void setCustomerGroups1(ArrayOfCustomerGroup value)
    {
        this.CustomerGroups1 = value;     
    }


    public  Customer(){}

    public Customer(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdCustomer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCustomer = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCustomer = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CustomerTypeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CustomerTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CustomerTypeCode = (String)obj;
                }
                else{
                    this.CustomerTypeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("CurrencyCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.CurrencyCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.CurrencyCode = (String)obj;
                }
                else{
                    this.CurrencyCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("Balance"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Balance = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.Balance = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DateCreated"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateCreated = j.toString();
                        //this.DateCreated = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.DateCreated = (String) obj;
                    //this.DateCreated = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdRegistration"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdRegistration = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdRegistration = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("BalanceUnavailable"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.BalanceUnavailable = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.BalanceUnavailable = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EneoContractNo"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EneoContractNo = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.EneoContractNo = (String)obj;
                }
                else{
                    this.EneoContractNo = "";
                }
            }
            return true;
        }
        if (info.name.equals("EneoPercentage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EneoPercentage = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.EneoPercentage = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("TopUpPercentage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.TopUpPercentage = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.TopUpPercentage = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GravityId"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GravityId = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.GravityId = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("GravityCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GravityCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GravityCode = (String)obj;
                }
                else{
                    this.GravityCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("GravityPercentage"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GravityPercentage = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.GravityPercentage = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("AccountOperationRequests"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AccountOperationRequests = (ArrayOfAccountOperationRequest)__envelope.get(j,ArrayOfAccountOperationRequest.class,false);
            }
            return true;
        }
        if (info.name.equals("Activations"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Activations = (ArrayOfActivation)__envelope.get(j,ArrayOfActivation.class,false);
            }
            return true;
        }
        if (info.name.equals("IssuedBills"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.IssuedBills = (ArrayOfBill)__envelope.get(j,ArrayOfBill.class,false);
            }
            return true;
        }
        if (info.name.equals("PayedBills"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PayedBills = (ArrayOfBill)__envelope.get(j,ArrayOfBill.class,false);
            }
            return true;
        }
        if (info.name.equals("Business"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Business = (Business)__envelope.get(j,Business.class,false);
            }
            return true;
        }
        if (info.name.equals("Currency"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Currency = (Currency)__envelope.get(j,Currency.class,false);
            }
            return true;
        }
        if (info.name.equals("Registration"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Registration = (Registration)__envelope.get(j,Registration.class,false);
            }
            return true;
        }
        if (info.name.equals("RefCustomerType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefCustomerType = (RefCustomerType)__envelope.get(j,RefCustomerType.class,false);
            }
            return true;
        }
        if (info.name.equals("MobileDevices"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MobileDevices = (ArrayOfMobileDevice)__envelope.get(j,ArrayOfMobileDevice.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerAddresses"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerAddresses = (ArrayOfCustomerAddress)__envelope.get(j,ArrayOfCustomerAddress.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerBalanceHistories"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerBalanceHistories = (ArrayOfCustomerBalanceHistory)__envelope.get(j,ArrayOfCustomerBalanceHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerGroups"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerGroups = (ArrayOfCustomerGroup)__envelope.get(j,ArrayOfCustomerGroup.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerImage"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerImage = (CustomerImage)__envelope.get(j,CustomerImage.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerLogin"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerLogin = (CustomerLogin)__envelope.get(j,CustomerLogin.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerTags"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerTags = (ArrayOfCustomerTag)__envelope.get(j,ArrayOfCustomerTag.class,false);
            }
            return true;
        }
        if (info.name.equals("EneoBillPayments"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.EneoBillPayments = (ArrayOfEneoBillPayment)__envelope.get(j,ArrayOfEneoBillPayment.class,false);
            }
            return true;
        }
        if (info.name.equals("ExternalAccounts"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ExternalAccounts = (ArrayOfExternalAccount)__envelope.get(j,ArrayOfExternalAccount.class,false);
            }
            return true;
        }
        if (info.name.equals("KoloNotifications"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.KoloNotifications = (ArrayOfKoloNotification)__envelope.get(j,ArrayOfKoloNotification.class,false);
            }
            return true;
        }
        if (info.name.equals("Partner"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Partner = (Partner)__envelope.get(j,Partner.class,false);
            }
            return true;
        }
        if (info.name.equals("Person"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Person = (Person)__envelope.get(j,Person.class,false);
            }
            return true;
        }
        if (info.name.equals("RecurringContributions"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RecurringContributions = (ArrayOfRecurringContribution)__envelope.get(j,ArrayOfRecurringContribution.class,false);
            }
            return true;
        }
        if (info.name.equals("TopUps"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TopUps = (ArrayOfTopUp)__envelope.get(j,ArrayOfTopUp.class,false);
            }
            return true;
        }
        if (info.name.equals("TransferGravities"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransferGravities = (ArrayOfTransferGravity)__envelope.get(j,ArrayOfTransferGravity.class,false);
            }
            return true;
        }
        if (info.name.equals("Transfert2CashDetails"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Transfert2CashDetails = (ArrayOfTransfert2CashDetail)__envelope.get(j,ArrayOfTransfert2CashDetail.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertE2e"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertE2e = (ArrayOfTransfertE2e)__envelope.get(j,ArrayOfTransfertE2e.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertGroups"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertGroups = (ArrayOfTransfertGroup)__envelope.get(j,ArrayOfTransfertGroup.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertGroupScheduleds"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertGroupScheduleds = (ArrayOfTransfertGroupScheduled)__envelope.get(j,ArrayOfTransfertGroupScheduled.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceivedTransfertP2p"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceivedTransfertP2p = (ArrayOfTransfertP2p)__envelope.get(j,ArrayOfTransfertP2p.class,false);
            }
            return true;
        }
        if (info.name.equals("SentTransfertP2p"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SentTransfertP2p = (ArrayOfTransfertP2p)__envelope.get(j,ArrayOfTransfertP2p.class,false);
            }
            return true;
        }
        if (info.name.equals("ReceivedTransfertScheduleds"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ReceivedTransfertScheduleds = (ArrayOfTransfertScheduled)__envelope.get(j,ArrayOfTransfertScheduled.class,false);
            }
            return true;
        }
        if (info.name.equals("SentTransfertScheduleds"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.SentTransfertScheduleds = (ArrayOfTransfertScheduled)__envelope.get(j,ArrayOfTransfertScheduled.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerGroups1"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerGroups1 = (ArrayOfCustomerGroup)__envelope.get(j,ArrayOfCustomerGroup.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdCustomer;
        }
        else if(propertyIndex==1)
        {
            return this.CustomerTypeCode!=null?this.CustomerTypeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.CurrencyCode!=null?this.CurrencyCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.Balance;
        }
        else if(propertyIndex==4)
        {
            return this.DateCreated!=null?this.DateCreated:SoapPrimitive.NullSkip;
            //return this.DateCreated!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.DateCreated):SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.IdRegistration!=null?this.IdRegistration:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==6)
        {
            return this.BalanceUnavailable;
        }
        else if(propertyIndex==7)
        {
            return this.EneoContractNo!=null?this.EneoContractNo:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.EneoPercentage!=null?this.EneoPercentage:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==9)
        {
            return this.TopUpPercentage!=null?this.TopUpPercentage:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==10)
        {
            return this.GravityId!=null?this.GravityId:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==11)
        {
            return this.GravityCode!=null?this.GravityCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==12)
        {
            return this.GravityPercentage!=null?this.GravityPercentage:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==13)
        {
            return this.AccountOperationRequests!=null?this.AccountOperationRequests:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==14)
        {
            return this.Activations!=null?this.Activations:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==15)
        {
            return this.IssuedBills!=null?this.IssuedBills:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==16)
        {
            return this.PayedBills!=null?this.PayedBills:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==17)
        {
            return this.Business!=null?this.Business:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==18)
        {
            return this.Currency!=null?this.Currency:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==19)
        {
            return this.Registration!=null?this.Registration:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==20)
        {
            return this.RefCustomerType!=null?this.RefCustomerType:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==21)
        {
            return this.MobileDevices!=null?this.MobileDevices:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==22)
        {
            return this.CustomerAddresses!=null?this.CustomerAddresses:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==23)
        {
            return this.CustomerBalanceHistories!=null?this.CustomerBalanceHistories:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==24)
        {
            return this.CustomerGroups!=null?this.CustomerGroups:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==25)
        {
            return this.CustomerImage!=null?this.CustomerImage:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==26)
        {
            return this.CustomerLogin!=null?this.CustomerLogin:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==27)
        {
            return this.CustomerTags!=null?this.CustomerTags:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==28)
        {
            return this.EneoBillPayments!=null?this.EneoBillPayments:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==29)
        {
            return this.ExternalAccounts!=null?this.ExternalAccounts:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==30)
        {
            return this.KoloNotifications!=null?this.KoloNotifications:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==31)
        {
            return this.Partner!=null?this.Partner:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==32)
        {
            return this.Person!=null?this.Person:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==33)
        {
            return this.RecurringContributions!=null?this.RecurringContributions:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==34)
        {
            return this.TopUps!=null?this.TopUps:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==35)
        {
            return this.TransferGravities!=null?this.TransferGravities:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==36)
        {
            return this.Transfert2CashDetails!=null?this.Transfert2CashDetails:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==37)
        {
            return this.TransfertE2e!=null?this.TransfertE2e:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==38)
        {
            return this.TransfertGroups!=null?this.TransfertGroups:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==39)
        {
            return this.TransfertGroupScheduleds!=null?this.TransfertGroupScheduleds:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==40)
        {
            return this.ReceivedTransfertP2p!=null?this.ReceivedTransfertP2p:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==41)
        {
            return this.SentTransfertP2p!=null?this.SentTransfertP2p:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==42)
        {
            return this.ReceivedTransfertScheduleds!=null?this.ReceivedTransfertScheduleds:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==43)
        {
            return this.SentTransfertScheduleds!=null?this.SentTransfertScheduleds:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==44)
        {
            return this.CustomerGroups1!=null?this.CustomerGroups1:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 45;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCustomer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CustomerTypeCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CurrencyCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Balance";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateCreated";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdRegistration";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "BalanceUnavailable";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EneoContractNo";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "EneoPercentage";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "TopUpPercentage";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "GravityId";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GravityCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "GravityPercentage";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==13)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "AccountOperationRequests";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==14)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Activations";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==15)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "IssuedBills";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==16)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "PayedBills";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==17)
        {
            info.type = Business.class;
            info.name = "Business";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==18)
        {
            info.type = Currency.class;
            info.name = "Currency";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==19)
        {
            info.type = Registration.class;
            info.name = "Registration";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==20)
        {
            info.type = RefCustomerType.class;
            info.name = "RefCustomerType";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==21)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "MobileDevices";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==22)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerAddresses";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==23)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerBalanceHistories";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==24)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerGroups";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==25)
        {
            info.type = CustomerImage.class;
            info.name = "CustomerImage";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==26)
        {
            info.type = CustomerLogin.class;
            info.name = "CustomerLogin";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==27)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerTags";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==28)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "EneoBillPayments";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==29)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ExternalAccounts";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==30)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "KoloNotifications";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==31)
        {
            info.type = Partner.class;
            info.name = "Partner";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==32)
        {
            info.type = Person.class;
            info.name = "Person";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==33)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "RecurringContributions";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==34)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TopUps";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==35)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransferGravities";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==36)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Transfert2CashDetails";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==37)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertE2e";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==38)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertGroups";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==39)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertGroupScheduleds";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==40)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ReceivedTransfertP2p";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==41)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "SentTransfertP2p";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==42)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ReceivedTransfertScheduleds";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==43)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "SentTransfertScheduleds";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==44)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerGroups1";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    public int getTotalBalance() {
        return Balance + BalanceUnavailable;
    }
}
