package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class CustomerBalanceHistory implements KvmSerializable {
	
	private int idCustomerHistory;
	private int idCustomerAccount;
	private String operationTypeCode;
	private String historyDate;
	private int oldBalance;
	private int newBalance;
	private int amount;
	private Customer customer;
	private RefOperationType refOperationType;
	
	public CustomerBalanceHistory() {
	}
	
	public CustomerBalanceHistory(SoapObject soapObject) {
		if (soapObject == null)
			return;
		if (soapObject.hasProperty("IdCustomerHistory")) {
			Object obj = soapObject.getProperty("IdCustomerHistory");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setIdCustomerHistory(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setIdCustomerHistory((Integer) obj);
			}
		}
		if (soapObject.hasProperty("IdCustomerAccount")) {
			Object obj = soapObject.getProperty("IdCustomerAccount");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setIdCustomerAccount(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setIdCustomerAccount((Integer) obj);
			}
		}
		if (soapObject.hasProperty("OperationTypeCode")) {
			Object obj = soapObject.getProperty("OperationTypeCode");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setOperationTypeCode(j.toString());
			} else if (obj != null && obj instanceof String) {
				setOperationTypeCode((String) obj);
			}
		}
		if (soapObject.hasProperty("HistoryDate")) {
			Object obj = soapObject.getProperty("HistoryDate");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setHistoryDate(j.toString());
			} else if (obj != null && obj instanceof String) {
				setHistoryDate((String) obj);
			}
		}
		if (soapObject.hasProperty("OldBalance")) {
			Object obj = soapObject.getProperty("OldBalance");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setOldBalance(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setOldBalance((Integer) obj);
			}
		}
		if (soapObject.hasProperty("NewBalance")) {
			Object obj = soapObject.getProperty("NewBalance");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setNewBalance(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setNewBalance((Integer) obj);
			}
		}
		if (soapObject.hasProperty("Amount")) {
			Object obj = soapObject.getProperty("Amount");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setAmount(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setAmount((Integer) obj);
			}
		}
		if (soapObject.hasProperty("Customer")) {
			SoapObject j = (SoapObject) soapObject.getProperty("Customer");
			setCustomer(new Customer(j));
			
		}
		if (soapObject.hasProperty("RefOperationType")) {
			SoapObject j = (SoapObject) soapObject.getProperty("RefOperationType");
			setRefOperationType(new RefOperationType(j));
			
		}
	}
	
	@Override
	public Object getProperty(int arg0) {
		switch (arg0) {
			case 0:
				return getIdCustomerHistory();
			case 1:
				return getIdCustomerAccount();
			case 2:
				return getOperationTypeCode();
			case 3:
				return getHistoryDate();
			case 4:
				return getOldBalance();
			case 5:
				return getNewBalance();
			case 6:
				return getAmount();
			case 7:
				return getCustomer();
			case 8:
				return getRefOperationType();
		}
		return null;
	}
	
	@Override
	public int getPropertyCount() {
		return 9;
	}
	
	@Override
	public void setProperty(int arg0, Object arg1) {
	}
	
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		switch (index) {
			case 0:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "IdCustomerHistory";
				break;
			case 1:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "IdCustomerAccount";
				break;
			case 2:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "OperationTypeCode";
				break;
			case 3:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "HistoryDate";
				break;
			case 4:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "OldBalance";
				break;
			case 5:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "NewBalance";
				break;
			case 6:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "Amount";
				break;
			case 7:
				info.type = Customer.class;
				info.name = "Customer";
				break;
			case 8:
				info.type = RefOperationType.class;
				info.name = "RefOperationType";
				break;
		}
	}
	
	public int getIdCustomerHistory() {
		return idCustomerHistory;
	}
	
	public void setIdCustomerHistory(int idCustomerHistory) {
		this.idCustomerHistory = idCustomerHistory;
	}
	
	public int getIdCustomerAccount() {
		return idCustomerAccount;
	}
	
	public void setIdCustomerAccount(int idCustomerAccount) {
		this.idCustomerAccount = idCustomerAccount;
	}
	
	public String getOperationTypeCode() {
		return operationTypeCode;
	}
	
	public void setOperationTypeCode(String operationTypeCode) {
		this.operationTypeCode = operationTypeCode;
	}
	
	public String getHistoryDate() {
		return historyDate;
	}
	
	public void setHistoryDate(String historyDate) {
		this.historyDate = historyDate;
	}
	
	public int getOldBalance() {
		return oldBalance;
	}
	
	public void setOldBalance(int oldBalance) {
		this.oldBalance = oldBalance;
	}
	
	public int getNewBalance() {
		return newBalance;
	}
	
	public void setNewBalance(int newBalance) {
		this.newBalance = newBalance;
	}
	
	public int getAmount() {
		return amount;
	}
	
	public void setAmount(int amount) {
		this.amount = amount;
	}
	
	public Customer getCustomer() {
		return customer;
	}
	
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	public RefOperationType getRefOperationType() {
		return refOperationType;
	}
	
	public void setRefOperationType(RefOperationType refOperationType) {
		this.refOperationType = refOperationType;
	}
	
	//    @Override
	public String getInnerText() {
		return null;
	}
	
	//    @Override
	public void setInnerText(String s) {
	}
}
