package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CustomerLogin extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdCustomer=0;
    
    private String Number;
    
    private Boolean NumberVerified;
    
    private String EmailAddress;
    
    private Boolean EmailAddressVerified=false;
    
    private String PwdSalt;
    
    private String Pwd;
    
    private String RecoveryToken;
    
    private String RecoveryTokenExpiryDate;
    //private java.util.Date RecoveryTokenExpiryDate;

    private String LoginStatusCode;
    
    private Customer Customer;
    
    private RefLoginStatu RefLoginStatu;
    
    private ArrayOfLoginAttempt LoginAttempts;
    
    public Integer getIdCustomer()
    {
        return this.IdCustomer;
    }
    
    public void setIdCustomer(Integer value)
    {
        this.IdCustomer = value;     
    }
    
    public String getNumber()
    {
        return this.Number;
    }
    
    public void setNumber(String value)
    {
        this.Number = value;     
    }
    
    public Boolean getNumberVerified()
    {
        return this.NumberVerified;
    }
    
    public void setNumberVerified(Boolean value)
    {
        this.NumberVerified = value;     
    }
    
    public String getEmailAddress()
    {
        return this.EmailAddress;
    }
    
    public void setEmailAddress(String value)
    {
        this.EmailAddress = value;     
    }
    
    public Boolean getEmailAddressVerified()
    {
        return this.EmailAddressVerified;
    }
    
    public void setEmailAddressVerified(Boolean value)
    {
        this.EmailAddressVerified = value;     
    }
    
    public String getPwdSalt()
    {
        return this.PwdSalt;
    }
    
    public void setPwdSalt(String value)
    {
        this.PwdSalt = value;     
    }
    
    public String getPwd()
    {
        return this.Pwd;
    }
    
    public void setPwd(String value)
    {
        this.Pwd = value;     
    }
    
    public String getRecoveryToken()
    {
        return this.RecoveryToken;
    }
    
    public void setRecoveryToken(String value)
    {
        this.RecoveryToken = value;     
    }
    
//    public java.util.Date getRecoveryTokenExpiryDate()
//    {
//        return this.RecoveryTokenExpiryDate;
//    }
//
//    public void setRecoveryTokenExpiryDate(java.util.Date value)
//    {
//        this.RecoveryTokenExpiryDate = value;
//    }

    public String getRecoveryTokenExpiryDate()
    {
        return this.RecoveryTokenExpiryDate;
    }

    public void setRecoveryTokenExpiryDate(String value)
    {
        this.RecoveryTokenExpiryDate = value;
    }
    
    public String getLoginStatusCode()
    {
        return this.LoginStatusCode;
    }
    
    public void setLoginStatusCode(String value)
    {
        this.LoginStatusCode = value;     
    }
    
    public Customer getCustomer()
    {
        return this.Customer;
    }
    
    public void setCustomer(Customer value)
    {
        this.Customer = value;     
    }
    
    public RefLoginStatu getRefLoginStatu()
    {
        return this.RefLoginStatu;
    }
    
    public void setRefLoginStatu(RefLoginStatu value)
    {
        this.RefLoginStatu = value;     
    }
    
    public ArrayOfLoginAttempt getLoginAttempts()
    {
        return this.LoginAttempts;
    }
    
    public void setLoginAttempts(ArrayOfLoginAttempt value)
    {
        this.LoginAttempts = value;     
    }

    public CustomerLogin(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdCustomer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCustomer = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCustomer = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Number"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Number = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Number = (String)obj;
                }
                else{
                    this.Number = "";
                }
            }
            return true;
        }
        if (info.name.equals("NumberVerified"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.NumberVerified = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.NumberVerified = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("EmailAddress"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EmailAddress = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.EmailAddress = (String)obj;
                }
                else{
                    this.EmailAddress = "";
                }
            }
            return true;
        }
        if (info.name.equals("EmailAddressVerified"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.EmailAddressVerified = Boolean.valueOf(j.toString());
                    }
                }
                else if (obj instanceof Boolean){
                    this.EmailAddressVerified = (Boolean)obj;
                }
            }
            return true;
        }
        if (info.name.equals("PwdSalt"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.PwdSalt = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.PwdSalt = (String)obj;
                }
                else{
                    this.PwdSalt = "";
                }
            }
            return true;
        }
        if (info.name.equals("Pwd"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Pwd = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Pwd = (String)obj;
                }
                else{
                    this.Pwd = "";
                }
            }
            return true;
        }
        if (info.name.equals("RecoveryToken"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RecoveryToken = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RecoveryToken = (String)obj;
                }
                else{
                    this.RecoveryToken = "";
                }
            }
            return true;
        }
        if (info.name.equals("RecoveryTokenExpiryDate"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RecoveryTokenExpiryDate = j.toString();
                        //this.RecoveryTokenExpiryDate = ExtendedSoapSerializationEnvelope.getDateTimeConverter().convertDateTime(j.toString());
                    }
                }
                else if (obj instanceof String){
                    this.RecoveryTokenExpiryDate = (String)obj;
                    //this.RecoveryTokenExpiryDate = (java.util.Date)obj;
                }
            }
            return true;
        }
        if (info.name.equals("LoginStatusCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.LoginStatusCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.LoginStatusCode = (String)obj;
                }
                else{
                    this.LoginStatusCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("Customer"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Customer = (Customer)__envelope.get(j,Customer.class,false);
            }
            return true;
        }
        if (info.name.equals("RefLoginStatu"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefLoginStatu = (RefLoginStatu)__envelope.get(j,RefLoginStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("LoginAttempts"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LoginAttempts = (ArrayOfLoginAttempt)__envelope.get(j,ArrayOfLoginAttempt.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdCustomer;
        }
        else if(propertyIndex==1)
        {
            return this.Number!=null?this.Number:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.NumberVerified!=null?this.NumberVerified:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==3)
        {
            return this.EmailAddress!=null?this.EmailAddress:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.EmailAddressVerified;
        }
        else if(propertyIndex==5)
        {
            return this.PwdSalt!=null?this.PwdSalt:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.Pwd!=null?this.Pwd:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.RecoveryToken!=null?this.RecoveryToken:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.RecoveryTokenExpiryDate!=null?this.RecoveryTokenExpiryDate:SoapPrimitive.NullNilElement;
            //return this.RecoveryTokenExpiryDate!=null?ExtendedSoapSerializationEnvelope.getDateTimeConverter().getStringFromDateTime(this.RecoveryTokenExpiryDate):SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==9)
        {
            return this.LoginStatusCode!=null?this.LoginStatusCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.Customer!=null?this.Customer:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==11)
        {
            return this.RefLoginStatu!=null?this.RefLoginStatu:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==12)
        {
            return this.LoginAttempts!=null?this.LoginAttempts:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 13;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCustomer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Number";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "NumberVerified";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "EmailAddress";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "EmailAddressVerified";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PwdSalt";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Pwd";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RecoveryToken";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RecoveryTokenExpiryDate";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LoginStatusCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = Customer.class;
            info.name = "Customer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==11)
        {
            info.type = RefLoginStatu.class;
            info.name = "RefLoginStatu";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==12)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "LoginAttempts";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
