package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ExternalAccount extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdExternalAccount=0;
    
    private String ExternalLogin;
    
    private String ExternalPwd;
    
    private String ExternalAccountTypeCode;
    
    private Integer IdCreditCard;
    
    private Integer IdCustomer=0;
    
    private CreditCardInfo CreditCardInfo;
    
    private Customer Customer;
    
    private ArrayOfExternalAccountHistory ExternalAccountHistories;
    
    private RefExternalAccountType RefExternalAccountType;
    
    private ArrayOfTransfertE2e TransfertE2e;
    
    private ArrayOfTransfertE2e TransfertE2e1;
    
    public Integer getIdExternalAccount()
    {
        return this.IdExternalAccount;
    }
    
    public void setIdExternalAccount(Integer value)
    {
        this.IdExternalAccount = value;     
    }
    
    public String getExternalLogin()
    {
        return this.ExternalLogin;
    }
    
    public void setExternalLogin(String value)
    {
        this.ExternalLogin = value;     
    }
    
    public String getExternalPwd()
    {
        return this.ExternalPwd;
    }
    
    public void setExternalPwd(String value)
    {
        this.ExternalPwd = value;     
    }
    
    public String getExternalAccountTypeCode()
    {
        return this.ExternalAccountTypeCode;
    }
    
    public void setExternalAccountTypeCode(String value)
    {
        this.ExternalAccountTypeCode = value;     
    }
    
    public Integer getIdCreditCard()
    {
        return this.IdCreditCard;
    }
    
    public void setIdCreditCard(Integer value)
    {
        this.IdCreditCard = value;     
    }
    
    public Integer getIdCustomer()
    {
        return this.IdCustomer;
    }
    
    public void setIdCustomer(Integer value)
    {
        this.IdCustomer = value;     
    }
    
    public CreditCardInfo getCreditCardInfo()
    {
        return this.CreditCardInfo;
    }
    
    public void setCreditCardInfo(CreditCardInfo value)
    {
        this.CreditCardInfo = value;     
    }
    
    public Customer getCustomer()
    {
        return this.Customer;
    }
    
    public void setCustomer(Customer value)
    {
        this.Customer = value;     
    }
    
    public ArrayOfExternalAccountHistory getExternalAccountHistories()
    {
        return this.ExternalAccountHistories;
    }
    
    public void setExternalAccountHistories(ArrayOfExternalAccountHistory value)
    {
        this.ExternalAccountHistories = value;     
    }
    
    public RefExternalAccountType getRefExternalAccountType()
    {
        return this.RefExternalAccountType;
    }
    
    public void setRefExternalAccountType(RefExternalAccountType value)
    {
        this.RefExternalAccountType = value;     
    }
    
    public ArrayOfTransfertE2e getTransfertE2e()
    {
        return this.TransfertE2e;
    }
    
    public void setTransfertE2e(ArrayOfTransfertE2e value)
    {
        this.TransfertE2e = value;     
    }
    
    public ArrayOfTransfertE2e getTransfertE2e1()
    {
        return this.TransfertE2e1;
    }
    
    public void setTransfertE2e1(ArrayOfTransfertE2e value)
    {
        this.TransfertE2e1 = value;     
    }


    public ExternalAccount(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdExternalAccount"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdExternalAccount = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdExternalAccount = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("ExternalLogin"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExternalLogin = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ExternalLogin = (String)obj;
                }
                else{
                    this.ExternalLogin = "";
                }
            }
            return true;
        }
        if (info.name.equals("ExternalPwd"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExternalPwd = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ExternalPwd = (String)obj;
                }
                else{
                    this.ExternalPwd = "";
                }
            }
            return true;
        }
        if (info.name.equals("ExternalAccountTypeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ExternalAccountTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ExternalAccountTypeCode = (String)obj;
                }
                else{
                    this.ExternalAccountTypeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("IdCreditCard"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCreditCard = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCreditCard = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdCustomer"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCustomer = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCustomer = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("CreditCardInfo"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CreditCardInfo = (CreditCardInfo)__envelope.get(j,CreditCardInfo.class,false);
            }
            return true;
        }
        if (info.name.equals("Customer"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Customer = (Customer)__envelope.get(j,Customer.class,false);
            }
            return true;
        }
        if (info.name.equals("ExternalAccountHistories"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.ExternalAccountHistories = (ArrayOfExternalAccountHistory)__envelope.get(j,ArrayOfExternalAccountHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("RefExternalAccountType"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.RefExternalAccountType = (RefExternalAccountType)__envelope.get(j,RefExternalAccountType.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertE2e"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertE2e = (ArrayOfTransfertE2e)__envelope.get(j,ArrayOfTransfertE2e.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertE2e1"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertE2e1 = (ArrayOfTransfertE2e)__envelope.get(j,ArrayOfTransfertE2e.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdExternalAccount;
        }
        else if(propertyIndex==1)
        {
            return this.ExternalLogin!=null?this.ExternalLogin:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.ExternalPwd!=null?this.ExternalPwd:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.ExternalAccountTypeCode!=null?this.ExternalAccountTypeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.IdCreditCard!=null?this.IdCreditCard:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==5)
        {
            return this.IdCustomer;
        }
        else if(propertyIndex==6)
        {
            return this.CreditCardInfo!=null?this.CreditCardInfo:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.Customer!=null?this.Customer:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.ExternalAccountHistories!=null?this.ExternalAccountHistories:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==9)
        {
            return this.RefExternalAccountType!=null?this.RefExternalAccountType:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.TransfertE2e!=null?this.TransfertE2e:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==11)
        {
            return this.TransfertE2e1!=null?this.TransfertE2e1:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdExternalAccount";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExternalLogin";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExternalPwd";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ExternalAccountTypeCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCreditCard";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCustomer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = CreditCardInfo.class;
            info.name = "CreditCardInfo";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = Customer.class;
            info.name = "Customer";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ExternalAccountHistories";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = RefExternalAccountType.class;
            info.name = "RefExternalAccountType";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertE2e";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==11)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertE2e1";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
