package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class KoloGroup extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String GroupCode;
    
    private String GroupDescription;
    
    private ArrayOfKoloPermission KoloPermissions;
    
    private ArrayOfKoloUser KoloUsers;
    
    public String getGroupCode()
    {
        return this.GroupCode;
    }
    
    public void setGroupCode(String value)
    {
        this.GroupCode = value;     
    }
    
    public String getGroupDescription()
    {
        return this.GroupDescription;
    }
    
    public void setGroupDescription(String value)
    {
        this.GroupDescription = value;     
    }
    
    public ArrayOfKoloPermission getKoloPermissions()
    {
        return this.KoloPermissions;
    }
    
    public void setKoloPermissions(ArrayOfKoloPermission value)
    {
        this.KoloPermissions = value;     
    }
    
    public ArrayOfKoloUser getKoloUsers()
    {
        return this.KoloUsers;
    }
    
    public void setKoloUsers(ArrayOfKoloUser value)
    {
        this.KoloUsers = value;     
    }


    public KoloGroup(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("GroupCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GroupCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GroupCode = (String)obj;
                }
                else{
                    this.GroupCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("GroupDescription"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.GroupDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.GroupDescription = (String)obj;
                }
                else{
                    this.GroupDescription = "";
                }
            }
            return true;
        }
        if (info.name.equals("KoloPermissions"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.KoloPermissions = (ArrayOfKoloPermission)__envelope.get(j,ArrayOfKoloPermission.class,false);
            }
            return true;
        }
        if (info.name.equals("KoloUsers"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.KoloUsers = (ArrayOfKoloUser)__envelope.get(j,ArrayOfKoloUser.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.GroupCode!=null?this.GroupCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.GroupDescription!=null?this.GroupDescription:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.KoloPermissions!=null?this.KoloPermissions:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.KoloUsers!=null?this.KoloUsers:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GroupCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "GroupDescription";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "KoloPermissions";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "KoloUsers";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
