package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class LoginAttempt implements KvmSerializable {
	
	private int idLoginAttempt;
	private int idCustomer;
	private String loginTime;
	private String resultCode;
	private String deviceId;
	private String simOperator;
	private String simSerialNumber;
	private String subscriberId;
	private String pwd;
	private String number;
	private double latitude;
	private double longitude;
	private double accuracy;
	private CustomerLogin customerLogin;
	private RefResult refResult;
	
	public LoginAttempt() {
	}
	
	public LoginAttempt(SoapObject soapObject) {
		if (soapObject == null)
			return;
		if (soapObject.hasProperty("IdLoginAttempt")) {
			Object obj = soapObject.getProperty("IdLoginAttempt");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setIdLoginAttempt(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setIdLoginAttempt((Integer) obj);
			}
		}
		if (soapObject.hasProperty("IdCustomer")) {
			Object obj = soapObject.getProperty("IdCustomer");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setIdCustomer(Integer.parseInt(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setIdCustomer((Integer) obj);
			}
		}
		if (soapObject.hasProperty("LoginTime")) {
			Object obj = soapObject.getProperty("LoginTime");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setLoginTime(j.toString());
			} else if (obj != null && obj instanceof String) {
				setLoginTime((String) obj);
			}
		}
		if (soapObject.hasProperty("ResultCode")) {
			Object obj = soapObject.getProperty("ResultCode");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setResultCode(j.toString());
			} else if (obj != null && obj instanceof String) {
				setResultCode((String) obj);
			}
		}
		if (soapObject.hasProperty("DeviceId")) {
			Object obj = soapObject.getProperty("DeviceId");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setDeviceId(j.toString());
			} else if (obj != null && obj instanceof String) {
				setDeviceId((String) obj);
			}
		}
		if (soapObject.hasProperty("SimOperator")) {
			Object obj = soapObject.getProperty("SimOperator");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setSimOperator(j.toString());
			} else if (obj != null && obj instanceof String) {
				setSimOperator((String) obj);
			}
		}
		if (soapObject.hasProperty("SimSerialNumber")) {
			Object obj = soapObject.getProperty("SimSerialNumber");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setSimSerialNumber(j.toString());
			} else if (obj != null && obj instanceof String) {
				setSimSerialNumber((String) obj);
			}
		}
		if (soapObject.hasProperty("SubscriberId")) {
			Object obj = soapObject.getProperty("SubscriberId");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setSubscriberId(j.toString());
			} else if (obj != null && obj instanceof String) {
				setSubscriberId((String) obj);
			}
		}
		if (soapObject.hasProperty("Pwd")) {
			Object obj = soapObject.getProperty("Pwd");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setPwd(j.toString());
			} else if (obj != null && obj instanceof String) {
				setPwd((String) obj);
			}
		}
		if (soapObject.hasProperty("Number")) {
			Object obj = soapObject.getProperty("Number");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setNumber(j.toString());
			} else if (obj != null && obj instanceof String) {
				setNumber((String) obj);
			}
		}
		if (soapObject.hasProperty("Latitude")) {
			Object obj = soapObject.getProperty("Latitude");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setLatitude(Double.parseDouble(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setLatitude((Double) obj);
			}
		}
		if (soapObject.hasProperty("Longitude")) {
			Object obj = soapObject.getProperty("Longitude");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setLongitude(Double.parseDouble(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setLongitude((Double) obj);
			}
		}
		if (soapObject.hasProperty("Accuracy")) {
			Object obj = soapObject.getProperty("Accuracy");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setAccuracy(Double.parseDouble(j.toString()));
			} else if (obj != null && obj instanceof Number) {
				setAccuracy((Double) obj);
			}
		}
		if (soapObject.hasProperty("CustomerLogin")) {
			SoapObject j = (SoapObject) soapObject.getProperty("CustomerLogin");
			setCustomerLogin(new CustomerLogin(j));
			
		}
		if (soapObject.hasProperty("RefResult")) {
			SoapObject j = (SoapObject) soapObject.getProperty("RefResult");
			setRefResult(new RefResult(j));
			
		}
	}
	
	@Override
	public Object getProperty(int arg0) {
		switch (arg0) {
			case 0:
				return getIdLoginAttempt();
			case 1:
				return getIdCustomer();
			case 2:
				return getLoginTime();
			case 3:
				return getResultCode();
			case 4:
				return getDeviceId();
			case 5:
				return getSimOperator();
			case 6:
				return getSimSerialNumber();
			case 7:
				return getSubscriberId();
			case 8:
				return getPwd();
			case 9:
				return getNumber();
			case 10:
				return getLatitude();
			case 11:
				return getLongitude();
			case 12:
				return getAccuracy();
			case 13:
				return getCustomerLogin();
			case 14:
				return getRefResult();
		}
		return null;
	}
	
	@Override
	public int getPropertyCount() {
		return 15;
	}
	
	@Override
	public void setProperty(int arg0, Object arg1) {
	}
	
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		switch (index) {
			case 0:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "IdLoginAttempt";
				break;
			case 1:
				info.type = PropertyInfo.INTEGER_CLASS;
				info.name = "IdCustomer";
				break;
			case 2:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "LoginTime";
				break;
			case 3:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "ResultCode";
				break;
			case 4:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "DeviceId";
				break;
			case 5:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "SimOperator";
				break;
			case 6:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "SimSerialNumber";
				break;
			case 7:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "SubscriberId";
				break;
			case 8:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "Pwd";
				break;
			case 9:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "Number";
				break;
			case 10:
				info.type = Double.class;
				info.name = "Latitude";
				break;
			case 11:
				info.type = Double.class;
				info.name = "Longitude";
				break;
			case 12:
				info.type = Double.class;
				info.name = "Accuracy";
				break;
			case 13:
				info.type = CustomerLogin.class;
				info.name = "CustomerLogin";
				break;
			case 14:
				info.type = RefResult.class;
				info.name = "RefResult";
				break;
		}
	}
	
	public int getIdLoginAttempt() {
		return idLoginAttempt;
	}
	
	public void setIdLoginAttempt(int idLoginAttempt) {
		this.idLoginAttempt = idLoginAttempt;
	}
	
	public int getIdCustomer() {
		return idCustomer;
	}
	
	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}
	
	public String getLoginTime() {
		return loginTime;
	}
	
	public void setLoginTime(String loginTime) {
		this.loginTime = loginTime;
	}
	
	public String getResultCode() {
		return resultCode;
	}
	
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}
	
	public String getDeviceId() {
		return deviceId;
	}
	
	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}
	
	public String getSimOperator() {
		return simOperator;
	}
	
	public void setSimOperator(String simOperator) {
		this.simOperator = simOperator;
	}
	
	public String getSimSerialNumber() {
		return simSerialNumber;
	}
	
	public void setSimSerialNumber(String simSerialNumber) {
		this.simSerialNumber = simSerialNumber;
	}
	
	public String getSubscriberId() {
		return subscriberId;
	}
	
	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}
	
	public String getPwd() {
		return pwd;
	}
	
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public String getNumber() {
		return number;
	}
	
	public void setNumber(String number) {
		this.number = number;
	}
	
	public double getLatitude() {
		return latitude;
	}
	
	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}
	
	public double getLongitude() {
		return longitude;
	}
	
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}
	
	public double getAccuracy() {
		return accuracy;
	}
	
	public void setAccuracy(double accuracy) {
		this.accuracy = accuracy;
	}
	
	public CustomerLogin getCustomerLogin() {
		return customerLogin;
	}
	
	public void setCustomerLogin(CustomerLogin customerLogin) {
		this.customerLogin = customerLogin;
	}
	
	public RefResult getRefResult() {
		return refResult;
	}
	
	public void setRefResult(RefResult refResult) {
		this.refResult = refResult;
	}
	
	//    @Override
	public String getInnerText() {
		return null;
	}
	
	//    @Override
	public void setInnerText(String s) {
	}
}
