package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class MasterUserHistory extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdMasterUserHistory=0;
    
    private Integer IdMasterUser=0;
    
    private Integer IdFees;
    
    private Integer IdCommission;
    
    private String DateCreation;
    
    private Commission Commission;
    
    private Fee Fee;
    
    private MasterUser MasterUser;
    
    public Integer getIdMasterUserHistory()
    {
        return this.IdMasterUserHistory;
    }
    
    public void setIdMasterUserHistory(Integer value)
    {
        this.IdMasterUserHistory = value;     
    }
    
    public Integer getIdMasterUser()
    {
        return this.IdMasterUser;
    }
    
    public void setIdMasterUser(Integer value)
    {
        this.IdMasterUser = value;     
    }
    
    public Integer getIdFees()
    {
        return this.IdFees;
    }
    
    public void setIdFees(Integer value)
    {
        this.IdFees = value;     
    }
    
    public Integer getIdCommission()
    {
        return this.IdCommission;
    }
    
    public void setIdCommission(Integer value)
    {
        this.IdCommission = value;     
    }
    
    public String getDateCreation()
    {
        return this.DateCreation;
    }
    
    public void setDateCreation(String value)
    {
        this.DateCreation = value;     
    }
    
    public Commission getCommission()
    {
        return this.Commission;
    }
    
    public void setCommission(Commission value)
    {
        this.Commission = value;     
    }
    
    public Fee getFee()
    {
        return this.Fee;
    }
    
    public void setFee(Fee value)
    {
        this.Fee = value;     
    }
    
    public MasterUser getMasterUser()
    {
        return this.MasterUser;
    }
    
    public void setMasterUser(MasterUser value)
    {
        this.MasterUser = value;     
    }


    public MasterUserHistory(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdMasterUserHistory"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdMasterUserHistory = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdMasterUserHistory = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdMasterUser"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdMasterUser = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdMasterUser = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdFees"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdFees = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdFees = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdCommission"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdCommission = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdCommission = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DateCreation"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateCreation = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DateCreation = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Commission"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Commission = (Commission)__envelope.get(j,Commission.class,false);
            }
            return true;
        }
        if (info.name.equals("Fee"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Fee = (Fee)__envelope.get(j,Fee.class,false);
            }
            return true;
        }
        if (info.name.equals("MasterUser"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.MasterUser = (MasterUser)__envelope.get(j,MasterUser.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdMasterUserHistory;
        }
        else if(propertyIndex==1)
        {
            return this.IdMasterUser;
        }
        else if(propertyIndex==2)
        {
            return this.IdFees!=null?this.IdFees:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==3)
        {
            return this.IdCommission!=null?this.IdCommission:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==4)
        {
            return this.DateCreation!=null?this.DateCreation:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==5)
        {
            return this.Commission!=null?this.Commission:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.Fee!=null?this.Fee:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.MasterUser!=null?this.MasterUser:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdMasterUserHistory";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdMasterUser";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdFees";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdCommission";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateCreation";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = Commission.class;
            info.name = "Commission";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = Fee.class;
            info.name = "Fee";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = MasterUser.class;
            info.name = "MasterUser";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
