package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class MyRefTypes extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private AccountOperation A1;
    
    private Currency A10;
    
    private Customer A11;
    
    private CustomerAddress A12;
    
    private CustomerBalanceHistory A13;
    
    private CustomerExternalAccount A14;
    
    private CustomerGroup A15;
    
    private CustomerImage A16;
    
    private CustomerLogin A17;
    
    private CustomerTag A18;
    
    private District A19;
    
    private AccountOperationRequest A2;
    
    private ExternalAccount A20;
    
    private ExternalAccountHistory A21;
    
    private KoloNotification A22;
    
    private GroupImage A23;
    
    private LoginAttempt A24;
    
    private MobileDevice A25;
    
    private Partner A26;
    
    private PartnerAddress A27;
    
    private PartnerBalanceHistory A28;
    
    private Person A29;
    
    private Adress A3;
    
    private PersonRelationship A30;
    
    private Provision A31;
    
    private RecurringContribution A32;
    
    private RefAddressType A33;
    
    private RefBillStatu A34;
    
    private RefBillType A35;
    
    private RefCustomerType A36;
    
    private RefExternalAccountType A37;
    
    private RefGender A38;
    
    private RefGroupType A39;
    
    private Bill A4;
    
    private RefIndustryCategory A40;
    
    private RefLoginStatu A41;
    
    private RefMaritalStatu A42;
    
    private RefOperationStatu A43;
    
    private RefOperationType A44;
    
    private RefPartnerType A45;
    
    private RefPersonRelationshipType A46;
    
    private RefProvisionStatu A47;
    
    private RefRegistrationStatu A48;
    
    private RefResult A49;
    
    private BillPayment A5;
    
    private RefTransfertStatu A50;
    
    private Registration A51;
    
    private Reseller A52;
    
    private Tag A53;
    
    private Transfert2Cash A54;
    
    private Transfert2CashDetail A55;
    
    private TransfertE2e A56;
    
    private TransfertGroup A57;
    
    private TransfertGroupScheduled A58;
    
    private TransfertP2p A59;
    
    private Business A6;
    
    private TransfertScheduled A60;
    
    private KoloUser A61;
    
    private Wholesaler A62;
    
    private BusinessContact A63;
    
    private City A64;
    
    private Country A65;
    
    private TopUp A66;
    
    private EneoBillPayment A67;
    
    private KoloMadCustomer A68;
    
    private KoloMadDetails A69;
    
    private CreditCardInfo A70;
    
    private KoloWsObjectOfObject A71;
    
    public AccountOperation getA1()
    {
        return this.A1;
    }
    
    public void setA1(AccountOperation value)
    {
        this.A1 = value;     
    }
    
    public Currency getA10()
    {
        return this.A10;
    }
    
    public void setA10(Currency value)
    {
        this.A10 = value;     
    }
    
    public Customer getA11()
    {
        return this.A11;
    }
    
    public void setA11(Customer value)
    {
        this.A11 = value;     
    }
    
    public CustomerAddress getA12()
    {
        return this.A12;
    }
    
    public void setA12(CustomerAddress value)
    {
        this.A12 = value;     
    }
    
    public CustomerBalanceHistory getA13()
    {
        return this.A13;
    }
    
    public void setA13(CustomerBalanceHistory value)
    {
        this.A13 = value;     
    }
    
    public CustomerExternalAccount getA14()
    {
        return this.A14;
    }
    
    public void setA14(CustomerExternalAccount value)
    {
        this.A14 = value;     
    }
    
    public CustomerGroup getA15()
    {
        return this.A15;
    }
    
    public void setA15(CustomerGroup value)
    {
        this.A15 = value;     
    }
    
    public CustomerImage getA16()
    {
        return this.A16;
    }
    
    public void setA16(CustomerImage value)
    {
        this.A16 = value;     
    }
    
    public CustomerLogin getA17()
    {
        return this.A17;
    }
    
    public void setA17(CustomerLogin value)
    {
        this.A17 = value;     
    }
    
    public CustomerTag getA18()
    {
        return this.A18;
    }
    
    public void setA18(CustomerTag value)
    {
        this.A18 = value;     
    }
    
    public District getA19()
    {
        return this.A19;
    }
    
    public void setA19(District value)
    {
        this.A19 = value;     
    }
    
    public AccountOperationRequest getA2()
    {
        return this.A2;
    }
    
    public void setA2(AccountOperationRequest value)
    {
        this.A2 = value;     
    }
    
    public ExternalAccount getA20()
    {
        return this.A20;
    }
    
    public void setA20(ExternalAccount value)
    {
        this.A20 = value;     
    }
    
    public ExternalAccountHistory getA21()
    {
        return this.A21;
    }
    
    public void setA21(ExternalAccountHistory value)
    {
        this.A21 = value;     
    }
    
    public KoloNotification getA22()
    {
        return this.A22;
    }
    
    public void setA22(KoloNotification value)
    {
        this.A22 = value;     
    }
    
    public GroupImage getA23()
    {
        return this.A23;
    }
    
    public void setA23(GroupImage value)
    {
        this.A23 = value;     
    }
    
    public LoginAttempt getA24()
    {
        return this.A24;
    }
    
    public void setA24(LoginAttempt value)
    {
        this.A24 = value;     
    }
    
    public MobileDevice getA25()
    {
        return this.A25;
    }
    
    public void setA25(MobileDevice value)
    {
        this.A25 = value;     
    }
    
    public Partner getA26()
    {
        return this.A26;
    }
    
    public void setA26(Partner value)
    {
        this.A26 = value;     
    }
    
    public PartnerAddress getA27()
    {
        return this.A27;
    }
    
    public void setA27(PartnerAddress value)
    {
        this.A27 = value;     
    }
    
    public PartnerBalanceHistory getA28()
    {
        return this.A28;
    }
    
    public void setA28(PartnerBalanceHistory value)
    {
        this.A28 = value;     
    }
    
    public Person getA29()
    {
        return this.A29;
    }
    
    public void setA29(Person value)
    {
        this.A29 = value;     
    }
    
    public Adress getA3()
    {
        return this.A3;
    }
    
    public void setA3(Adress value)
    {
        this.A3 = value;     
    }
    
    public PersonRelationship getA30()
    {
        return this.A30;
    }
    
    public void setA30(PersonRelationship value)
    {
        this.A30 = value;     
    }
    
    public Provision getA31()
    {
        return this.A31;
    }
    
    public void setA31(Provision value)
    {
        this.A31 = value;     
    }
    
    public RecurringContribution getA32()
    {
        return this.A32;
    }
    
    public void setA32(RecurringContribution value)
    {
        this.A32 = value;     
    }
    
    public RefAddressType getA33()
    {
        return this.A33;
    }
    
    public void setA33(RefAddressType value)
    {
        this.A33 = value;     
    }
    
    public RefBillStatu getA34()
    {
        return this.A34;
    }
    
    public void setA34(RefBillStatu value)
    {
        this.A34 = value;     
    }
    
    public RefBillType getA35()
    {
        return this.A35;
    }
    
    public void setA35(RefBillType value)
    {
        this.A35 = value;     
    }
    
    public RefCustomerType getA36()
    {
        return this.A36;
    }
    
    public void setA36(RefCustomerType value)
    {
        this.A36 = value;     
    }
    
    public RefExternalAccountType getA37()
    {
        return this.A37;
    }
    
    public void setA37(RefExternalAccountType value)
    {
        this.A37 = value;     
    }
    
    public RefGender getA38()
    {
        return this.A38;
    }
    
    public void setA38(RefGender value)
    {
        this.A38 = value;     
    }
    
    public RefGroupType getA39()
    {
        return this.A39;
    }
    
    public void setA39(RefGroupType value)
    {
        this.A39 = value;     
    }
    
    public Bill getA4()
    {
        return this.A4;
    }
    
    public void setA4(Bill value)
    {
        this.A4 = value;     
    }
    
    public RefIndustryCategory getA40()
    {
        return this.A40;
    }
    
    public void setA40(RefIndustryCategory value)
    {
        this.A40 = value;     
    }
    
    public RefLoginStatu getA41()
    {
        return this.A41;
    }
    
    public void setA41(RefLoginStatu value)
    {
        this.A41 = value;     
    }
    
    public RefMaritalStatu getA42()
    {
        return this.A42;
    }
    
    public void setA42(RefMaritalStatu value)
    {
        this.A42 = value;     
    }
    
    public RefOperationStatu getA43()
    {
        return this.A43;
    }
    
    public void setA43(RefOperationStatu value)
    {
        this.A43 = value;     
    }
    
    public RefOperationType getA44()
    {
        return this.A44;
    }
    
    public void setA44(RefOperationType value)
    {
        this.A44 = value;     
    }
    
    public RefPartnerType getA45()
    {
        return this.A45;
    }
    
    public void setA45(RefPartnerType value)
    {
        this.A45 = value;     
    }
    
    public RefPersonRelationshipType getA46()
    {
        return this.A46;
    }
    
    public void setA46(RefPersonRelationshipType value)
    {
        this.A46 = value;     
    }
    
    public RefProvisionStatu getA47()
    {
        return this.A47;
    }
    
    public void setA47(RefProvisionStatu value)
    {
        this.A47 = value;     
    }
    
    public RefRegistrationStatu getA48()
    {
        return this.A48;
    }
    
    public void setA48(RefRegistrationStatu value)
    {
        this.A48 = value;     
    }
    
    public RefResult getA49()
    {
        return this.A49;
    }
    
    public void setA49(RefResult value)
    {
        this.A49 = value;     
    }
    
    public BillPayment getA5()
    {
        return this.A5;
    }
    
    public void setA5(BillPayment value)
    {
        this.A5 = value;     
    }
    
    public RefTransfertStatu getA50()
    {
        return this.A50;
    }
    
    public void setA50(RefTransfertStatu value)
    {
        this.A50 = value;     
    }
    
    public Registration getA51()
    {
        return this.A51;
    }
    
    public void setA51(Registration value)
    {
        this.A51 = value;     
    }
    
    public Reseller getA52()
    {
        return this.A52;
    }
    
    public void setA52(Reseller value)
    {
        this.A52 = value;     
    }
    
    public Tag getA53()
    {
        return this.A53;
    }
    
    public void setA53(Tag value)
    {
        this.A53 = value;     
    }
    
    public Transfert2Cash getA54()
    {
        return this.A54;
    }
    
    public void setA54(Transfert2Cash value)
    {
        this.A54 = value;     
    }
    
    public Transfert2CashDetail getA55()
    {
        return this.A55;
    }
    
    public void setA55(Transfert2CashDetail value)
    {
        this.A55 = value;     
    }
    
    public TransfertE2e getA56()
    {
        return this.A56;
    }
    
    public void setA56(TransfertE2e value)
    {
        this.A56 = value;     
    }
    
    public TransfertGroup getA57()
    {
        return this.A57;
    }
    
    public void setA57(TransfertGroup value)
    {
        this.A57 = value;     
    }
    
    public TransfertGroupScheduled getA58()
    {
        return this.A58;
    }
    
    public void setA58(TransfertGroupScheduled value)
    {
        this.A58 = value;     
    }
    
    public TransfertP2p getA59()
    {
        return this.A59;
    }
    
    public void setA59(TransfertP2p value)
    {
        this.A59 = value;     
    }
    
    public Business getA6()
    {
        return this.A6;
    }
    
    public void setA6(Business value)
    {
        this.A6 = value;     
    }
    
    public TransfertScheduled getA60()
    {
        return this.A60;
    }
    
    public void setA60(TransfertScheduled value)
    {
        this.A60 = value;     
    }
    
    public KoloUser getA61()
    {
        return this.A61;
    }
    
    public void setA61(KoloUser value)
    {
        this.A61 = value;     
    }
    
    public Wholesaler getA62()
    {
        return this.A62;
    }
    
    public void setA62(Wholesaler value)
    {
        this.A62 = value;     
    }
    
    public BusinessContact getA63()
    {
        return this.A63;
    }
    
    public void setA63(BusinessContact value)
    {
        this.A63 = value;     
    }
    
    public City getA64()
    {
        return this.A64;
    }
    
    public void setA64(City value)
    {
        this.A64 = value;     
    }
    
    public Country getA65()
    {
        return this.A65;
    }
    
    public void setA65(Country value)
    {
        this.A65 = value;     
    }
    
    public TopUp getA66()
    {
        return this.A66;
    }
    
    public void setA66(TopUp value)
    {
        this.A66 = value;     
    }
    
    public EneoBillPayment getA67()
    {
        return this.A67;
    }
    
    public void setA67(EneoBillPayment value)
    {
        this.A67 = value;     
    }
    
    public KoloMadCustomer getA68()
    {
        return this.A68;
    }
    
    public void setA68(KoloMadCustomer value)
    {
        this.A68 = value;     
    }
    
    public KoloMadDetails getA69()
    {
        return this.A69;
    }
    
    public void setA69(KoloMadDetails value)
    {
        this.A69 = value;     
    }
    
    public CreditCardInfo getA70()
    {
        return this.A70;
    }
    
    public void setA70(CreditCardInfo value)
    {
        this.A70 = value;     
    }
    
    public KoloWsObjectOfObject getA71()
    {
        return this.A71;
    }
    
    public void setA71(KoloWsObjectOfObject value)
    {
        this.A71 = value;     
    }

    public MyRefTypes(){}

    public MyRefTypes(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("A1"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A1 = (AccountOperation)__envelope.get(j,AccountOperation.class,false);
            }
            return true;
        }
        if (info.name.equals("A10"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A10 = (Currency)__envelope.get(j,Currency.class,false);
            }
            return true;
        }
        if (info.name.equals("A11"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A11 = (Customer)__envelope.get(j,Customer.class,false);
            }
            return true;
        }
        if (info.name.equals("A12"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A12 = (CustomerAddress)__envelope.get(j,CustomerAddress.class,false);
            }
            return true;
        }
        if (info.name.equals("A13"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A13 = (CustomerBalanceHistory)__envelope.get(j,CustomerBalanceHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("A14"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A14 = (CustomerExternalAccount)__envelope.get(j,CustomerExternalAccount.class,false);
            }
            return true;
        }
        if (info.name.equals("A15"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A15 = (CustomerGroup)__envelope.get(j,CustomerGroup.class,false);
            }
            return true;
        }
        if (info.name.equals("A16"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A16 = (CustomerImage)__envelope.get(j,CustomerImage.class,false);
            }
            return true;
        }
        if (info.name.equals("A17"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A17 = (CustomerLogin)__envelope.get(j,CustomerLogin.class,false);
            }
            return true;
        }
        if (info.name.equals("A18"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A18 = (CustomerTag)__envelope.get(j,CustomerTag.class,false);
            }
            return true;
        }
        if (info.name.equals("A19"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A19 = (District)__envelope.get(j,District.class,false);
            }
            return true;
        }
        if (info.name.equals("A2"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A2 = (AccountOperationRequest)__envelope.get(j,AccountOperationRequest.class,false);
            }
            return true;
        }
        if (info.name.equals("A20"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A20 = (ExternalAccount)__envelope.get(j,ExternalAccount.class,false);
            }
            return true;
        }
        if (info.name.equals("A21"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A21 = (ExternalAccountHistory)__envelope.get(j,ExternalAccountHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("A22"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A22 = (KoloNotification)__envelope.get(j,KoloNotification.class,false);
            }
            return true;
        }
        if (info.name.equals("A23"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A23 = (GroupImage)__envelope.get(j,GroupImage.class,false);
            }
            return true;
        }
        if (info.name.equals("A24"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A24 = (LoginAttempt)__envelope.get(j,LoginAttempt.class,false);
            }
            return true;
        }
        if (info.name.equals("A25"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A25 = (MobileDevice)__envelope.get(j,MobileDevice.class,false);
            }
            return true;
        }
        if (info.name.equals("A26"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A26 = (Partner)__envelope.get(j,Partner.class,false);
            }
            return true;
        }
        if (info.name.equals("A27"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A27 = (PartnerAddress)__envelope.get(j,PartnerAddress.class,false);
            }
            return true;
        }
        if (info.name.equals("A28"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A28 = (PartnerBalanceHistory)__envelope.get(j,PartnerBalanceHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("A29"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A29 = (Person)__envelope.get(j,Person.class,false);
            }
            return true;
        }
        if (info.name.equals("A3"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A3 = (Adress)__envelope.get(j,Adress.class,false);
            }
            return true;
        }
        if (info.name.equals("A30"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A30 = (PersonRelationship)__envelope.get(j,PersonRelationship.class,false);
            }
            return true;
        }
        if (info.name.equals("A31"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A31 = (Provision)__envelope.get(j,Provision.class,false);
            }
            return true;
        }
        if (info.name.equals("A32"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A32 = (RecurringContribution)__envelope.get(j,RecurringContribution.class,false);
            }
            return true;
        }
        if (info.name.equals("A33"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A33 = (RefAddressType)__envelope.get(j,RefAddressType.class,false);
            }
            return true;
        }
        if (info.name.equals("A34"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A34 = (RefBillStatu)__envelope.get(j,RefBillStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A35"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A35 = (RefBillType)__envelope.get(j,RefBillType.class,false);
            }
            return true;
        }
        if (info.name.equals("A36"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A36 = (RefCustomerType)__envelope.get(j,RefCustomerType.class,false);
            }
            return true;
        }
        if (info.name.equals("A37"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A37 = (RefExternalAccountType)__envelope.get(j,RefExternalAccountType.class,false);
            }
            return true;
        }
        if (info.name.equals("A38"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A38 = (RefGender)__envelope.get(j,RefGender.class,false);
            }
            return true;
        }
        if (info.name.equals("A39"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A39 = (RefGroupType)__envelope.get(j,RefGroupType.class,false);
            }
            return true;
        }
        if (info.name.equals("A4"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A4 = (Bill)__envelope.get(j,Bill.class,false);
            }
            return true;
        }
        if (info.name.equals("A40"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A40 = (RefIndustryCategory)__envelope.get(j,RefIndustryCategory.class,false);
            }
            return true;
        }
        if (info.name.equals("A41"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A41 = (RefLoginStatu)__envelope.get(j,RefLoginStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A42"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A42 = (RefMaritalStatu)__envelope.get(j,RefMaritalStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A43"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A43 = (RefOperationStatu)__envelope.get(j,RefOperationStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A44"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A44 = (RefOperationType)__envelope.get(j,RefOperationType.class,false);
            }
            return true;
        }
        if (info.name.equals("A45"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A45 = (RefPartnerType)__envelope.get(j,RefPartnerType.class,false);
            }
            return true;
        }
        if (info.name.equals("A46"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A46 = (RefPersonRelationshipType)__envelope.get(j,RefPersonRelationshipType.class,false);
            }
            return true;
        }
        if (info.name.equals("A47"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A47 = (RefProvisionStatu)__envelope.get(j,RefProvisionStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A48"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A48 = (RefRegistrationStatu)__envelope.get(j,RefRegistrationStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A49"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A49 = (RefResult)__envelope.get(j,RefResult.class,false);
            }
            return true;
        }
        if (info.name.equals("A5"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A5 = (BillPayment)__envelope.get(j,BillPayment.class,false);
            }
            return true;
        }
        if (info.name.equals("A50"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A50 = (RefTransfertStatu)__envelope.get(j,RefTransfertStatu.class,false);
            }
            return true;
        }
        if (info.name.equals("A51"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A51 = (Registration)__envelope.get(j,Registration.class,false);
            }
            return true;
        }
        if (info.name.equals("A52"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A52 = (Reseller)__envelope.get(j,Reseller.class,false);
            }
            return true;
        }
        if (info.name.equals("A53"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A53 = (Tag)__envelope.get(j,Tag.class,false);
            }
            return true;
        }
        if (info.name.equals("A54"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A54 = (Transfert2Cash)__envelope.get(j,Transfert2Cash.class,false);
            }
            return true;
        }
        if (info.name.equals("A55"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A55 = (Transfert2CashDetail)__envelope.get(j,Transfert2CashDetail.class,false);
            }
            return true;
        }
        if (info.name.equals("A56"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A56 = (TransfertE2e)__envelope.get(j,TransfertE2e.class,false);
            }
            return true;
        }
        if (info.name.equals("A57"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A57 = (TransfertGroup)__envelope.get(j,TransfertGroup.class,false);
            }
            return true;
        }
        if (info.name.equals("A58"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A58 = (TransfertGroupScheduled)__envelope.get(j,TransfertGroupScheduled.class,false);
            }
            return true;
        }
        if (info.name.equals("A59"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A59 = (TransfertP2p)__envelope.get(j,TransfertP2p.class,false);
            }
            return true;
        }
        if (info.name.equals("A6"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A6 = (Business)__envelope.get(j,Business.class,false);
            }
            return true;
        }
        if (info.name.equals("A60"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A60 = (TransfertScheduled)__envelope.get(j,TransfertScheduled.class,false);
            }
            return true;
        }
        if (info.name.equals("A61"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A61 = (KoloUser)__envelope.get(j,KoloUser.class,false);
            }
            return true;
        }
        if (info.name.equals("A62"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A62 = (Wholesaler)__envelope.get(j,Wholesaler.class,false);
            }
            return true;
        }
        if (info.name.equals("A63"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A63 = (BusinessContact)__envelope.get(j,BusinessContact.class,false);
            }
            return true;
        }
        if (info.name.equals("A64"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A64 = (City)__envelope.get(j,City.class,false);
            }
            return true;
        }
        if (info.name.equals("A65"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A65 = (Country)__envelope.get(j,Country.class,false);
            }
            return true;
        }
        if (info.name.equals("A66"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A66 = (TopUp)__envelope.get(j,TopUp.class,false);
            }
            return true;
        }
        if (info.name.equals("A67"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A67 = (EneoBillPayment)__envelope.get(j,EneoBillPayment.class,false);
            }
            return true;
        }
        if (info.name.equals("A68"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A68 = (KoloMadCustomer)__envelope.get(j,KoloMadCustomer.class,false);
            }
            return true;
        }
        if (info.name.equals("A69"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A69 = (KoloMadDetails)__envelope.get(j,KoloMadDetails.class,false);
            }
            return true;
        }
        if (info.name.equals("A70"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A70 = (CreditCardInfo)__envelope.get(j,CreditCardInfo.class,false);
            }
            return true;
        }
        if (info.name.equals("A71"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.A71 = (KoloWsObjectOfObject)__envelope.get(j,KoloWsObjectOfObject.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.A1!=null?this.A1:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.A10!=null?this.A10:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.A11!=null?this.A11:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.A12!=null?this.A12:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.A13!=null?this.A13:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.A14!=null?this.A14:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==6)
        {
            return this.A15!=null?this.A15:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.A16!=null?this.A16:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.A17!=null?this.A17:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==9)
        {
            return this.A18!=null?this.A18:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==10)
        {
            return this.A19!=null?this.A19:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==11)
        {
            return this.A2!=null?this.A2:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==12)
        {
            return this.A20!=null?this.A20:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==13)
        {
            return this.A21!=null?this.A21:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==14)
        {
            return this.A22!=null?this.A22:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==15)
        {
            return this.A23!=null?this.A23:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==16)
        {
            return this.A24!=null?this.A24:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==17)
        {
            return this.A25!=null?this.A25:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==18)
        {
            return this.A26!=null?this.A26:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==19)
        {
            return this.A27!=null?this.A27:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==20)
        {
            return this.A28!=null?this.A28:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==21)
        {
            return this.A29!=null?this.A29:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==22)
        {
            return this.A3!=null?this.A3:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==23)
        {
            return this.A30!=null?this.A30:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==24)
        {
            return this.A31!=null?this.A31:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==25)
        {
            return this.A32!=null?this.A32:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==26)
        {
            return this.A33!=null?this.A33:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==27)
        {
            return this.A34!=null?this.A34:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==28)
        {
            return this.A35!=null?this.A35:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==29)
        {
            return this.A36!=null?this.A36:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==30)
        {
            return this.A37!=null?this.A37:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==31)
        {
            return this.A38!=null?this.A38:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==32)
        {
            return this.A39!=null?this.A39:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==33)
        {
            return this.A4!=null?this.A4:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==34)
        {
            return this.A40!=null?this.A40:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==35)
        {
            return this.A41!=null?this.A41:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==36)
        {
            return this.A42!=null?this.A42:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==37)
        {
            return this.A43!=null?this.A43:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==38)
        {
            return this.A44!=null?this.A44:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==39)
        {
            return this.A45!=null?this.A45:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==40)
        {
            return this.A46!=null?this.A46:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==41)
        {
            return this.A47!=null?this.A47:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==42)
        {
            return this.A48!=null?this.A48:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==43)
        {
            return this.A49!=null?this.A49:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==44)
        {
            return this.A5!=null?this.A5:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==45)
        {
            return this.A50!=null?this.A50:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==46)
        {
            return this.A51!=null?this.A51:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==47)
        {
            return this.A52!=null?this.A52:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==48)
        {
            return this.A53!=null?this.A53:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==49)
        {
            return this.A54!=null?this.A54:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==50)
        {
            return this.A55!=null?this.A55:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==51)
        {
            return this.A56!=null?this.A56:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==52)
        {
            return this.A57!=null?this.A57:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==53)
        {
            return this.A58!=null?this.A58:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==54)
        {
            return this.A59!=null?this.A59:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==55)
        {
            return this.A6!=null?this.A6:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==56)
        {
            return this.A60!=null?this.A60:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==57)
        {
            return this.A61!=null?this.A61:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==58)
        {
            return this.A62!=null?this.A62:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==59)
        {
            return this.A63!=null?this.A63:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==60)
        {
            return this.A64!=null?this.A64:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==61)
        {
            return this.A65!=null?this.A65:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==62)
        {
            return this.A66!=null?this.A66:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==63)
        {
            return this.A67!=null?this.A67:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==64)
        {
            return this.A68!=null?this.A68:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==65)
        {
            return this.A69!=null?this.A69:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==66)
        {
            return this.A70!=null?this.A70:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==67)
        {
            return this.A71!=null?this.A71:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 68;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = AccountOperation.class;
            info.name = "A1";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = Currency.class;
            info.name = "A10";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = Customer.class;
            info.name = "A11";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = CustomerAddress.class;
            info.name = "A12";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = CustomerBalanceHistory.class;
            info.name = "A13";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = CustomerExternalAccount.class;
            info.name = "A14";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = CustomerGroup.class;
            info.name = "A15";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = CustomerImage.class;
            info.name = "A16";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = CustomerLogin.class;
            info.name = "A17";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==9)
        {
            info.type = CustomerTag.class;
            info.name = "A18";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==10)
        {
            info.type = District.class;
            info.name = "A19";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==11)
        {
            info.type = AccountOperationRequest.class;
            info.name = "A2";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==12)
        {
            info.type = ExternalAccount.class;
            info.name = "A20";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==13)
        {
            info.type = ExternalAccountHistory.class;
            info.name = "A21";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==14)
        {
            info.type = KoloNotification.class;
            info.name = "A22";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==15)
        {
            info.type = GroupImage.class;
            info.name = "A23";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==16)
        {
            info.type = LoginAttempt.class;
            info.name = "A24";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==17)
        {
            info.type = MobileDevice.class;
            info.name = "A25";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==18)
        {
            info.type = Partner.class;
            info.name = "A26";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==19)
        {
            info.type = PartnerAddress.class;
            info.name = "A27";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==20)
        {
            info.type = PartnerBalanceHistory.class;
            info.name = "A28";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==21)
        {
            info.type = Person.class;
            info.name = "A29";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==22)
        {
            info.type = Adress.class;
            info.name = "A3";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==23)
        {
            info.type = PersonRelationship.class;
            info.name = "A30";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==24)
        {
            info.type = Provision.class;
            info.name = "A31";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==25)
        {
            info.type = RecurringContribution.class;
            info.name = "A32";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==26)
        {
            info.type = RefAddressType.class;
            info.name = "A33";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==27)
        {
            info.type = RefBillStatu.class;
            info.name = "A34";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==28)
        {
            info.type = RefBillType.class;
            info.name = "A35";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==29)
        {
            info.type = RefCustomerType.class;
            info.name = "A36";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==30)
        {
            info.type = RefExternalAccountType.class;
            info.name = "A37";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==31)
        {
            info.type = RefGender.class;
            info.name = "A38";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==32)
        {
            info.type = RefGroupType.class;
            info.name = "A39";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==33)
        {
            info.type = Bill.class;
            info.name = "A4";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==34)
        {
            info.type = RefIndustryCategory.class;
            info.name = "A40";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==35)
        {
            info.type = RefLoginStatu.class;
            info.name = "A41";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==36)
        {
            info.type = RefMaritalStatu.class;
            info.name = "A42";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==37)
        {
            info.type = RefOperationStatu.class;
            info.name = "A43";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==38)
        {
            info.type = RefOperationType.class;
            info.name = "A44";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==39)
        {
            info.type = RefPartnerType.class;
            info.name = "A45";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==40)
        {
            info.type = RefPersonRelationshipType.class;
            info.name = "A46";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==41)
        {
            info.type = RefProvisionStatu.class;
            info.name = "A47";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==42)
        {
            info.type = RefRegistrationStatu.class;
            info.name = "A48";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==43)
        {
            info.type = RefResult.class;
            info.name = "A49";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==44)
        {
            info.type = BillPayment.class;
            info.name = "A5";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==45)
        {
            info.type = RefTransfertStatu.class;
            info.name = "A50";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==46)
        {
            info.type = Registration.class;
            info.name = "A51";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==47)
        {
            info.type = Reseller.class;
            info.name = "A52";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==48)
        {
            info.type = Tag.class;
            info.name = "A53";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==49)
        {
            info.type = Transfert2Cash.class;
            info.name = "A54";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==50)
        {
            info.type = Transfert2CashDetail.class;
            info.name = "A55";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==51)
        {
            info.type = TransfertE2e.class;
            info.name = "A56";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==52)
        {
            info.type = TransfertGroup.class;
            info.name = "A57";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==53)
        {
            info.type = TransfertGroupScheduled.class;
            info.name = "A58";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==54)
        {
            info.type = TransfertP2p.class;
            info.name = "A59";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==55)
        {
            info.type = Business.class;
            info.name = "A6";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==56)
        {
            info.type = TransfertScheduled.class;
            info.name = "A60";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==57)
        {
            info.type = KoloUser.class;
            info.name = "A61";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==58)
        {
            info.type = Wholesaler.class;
            info.name = "A62";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==59)
        {
            info.type = BusinessContact.class;
            info.name = "A63";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==60)
        {
            info.type = City.class;
            info.name = "A64";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==61)
        {
            info.type = Country.class;
            info.name = "A65";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==62)
        {
            info.type = TopUp.class;
            info.name = "A66";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==63)
        {
            info.type = EneoBillPayment.class;
            info.name = "A67";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==64)
        {
            info.type = KoloMadCustomer.class;
            info.name = "A68";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==65)
        {
            info.type = KoloMadDetails.class;
            info.name = "A69";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==66)
        {
            info.type = CreditCardInfo.class;
            info.name = "A70";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==67)
        {
            info.type = KoloWsObjectOfObject.class;
            info.name = "A71";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
