package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.util.Hashtable;

public class MyRefTypes implements KvmSerializable {

    public AccountOperation a1;
    public Currency a10;
    public Customer a11;
    public CustomerAddress a12;
    public CustomerBalanceHistory a13;
    public CustomerExternalAccount a14;
    public CustomerGroup a15;
    public CustomerImage a16;
    public CustomerLogin a17;
    public CustomerTag a18;
    public District a19;
    public AccountOperationRequest a2;
    public ExternalAccount a20;
    public ExternalAccountHistory a21;
    public KoloNotification a22;
    public GroupImage a23;
    public LoginAttempt a24;
    public MobileDevice a25;
    public Partner a26;
    public PartnerAddress a27;
    public PartnerBalanceHistory a28;
    public Person a29;
    public Adresse a3;
    public PersonRelationship a30;
    public Provision a31;
    public RecurringContribution a32;
    public RefAddressType a33;
    public RefBillStatu a34;
    public RefBillType a35;
    public RefCustomerType a36;
    public RefExternalAccountType a37;
    public RefGender a38;
    public RefGroupType a39;
    public Bill a4;
    public RefIndustryCategory a40;
    public RefLoginStatu a41;
    public RefMaritalStatu a42;
    public RefOperationStatu a43;
    public RefOperationType a44;
    public RefPartnerType a45;
    public RefPersonRelationshipType a46;
    public RefProvisionStatu a47;
    public RefRegistrationStatu a48;
    public RefResult a49;
    public BillPayment a5;
    public RefTransfertStatu a50;
    public Registration a51;
    public Reseller a52;
    public Tag a53;
    public Transfert2Cash a54;
    public Transfert2CashDetails a55;
    public TransfertE2e a56;
    public TransfertGroup a57;
    public TransfertGroupScheduled a58;
    public TransfertP2p a59;
    public Business a6;
    public TransfertScheduled a60;
    public KoloUser a61;
    public Wholesaler a62;
    public BusinessContact a7;
    public City a8;
    public Country a9;

    public MyRefTypes() {
    }

    public MyRefTypes(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("a1")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a1");
            a1 = new AccountOperation(j);

        }
        if (soapObject.hasProperty("a10")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a10");
            a10 = new Currency(j);

        }
        if (soapObject.hasProperty("a11")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a11");
            a11 = new Customer(j);

        }
        if (soapObject.hasProperty("a12")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a12");
            a12 = new CustomerAddress(j);

        }
        if (soapObject.hasProperty("a13")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a13");
            a13 = new CustomerBalanceHistory(j);

        }
        if (soapObject.hasProperty("a14")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a14");
            a14 = new CustomerExternalAccount(j);

        }
        if (soapObject.hasProperty("a15")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a15");
            a15 = new CustomerGroup(j);

        }
        if (soapObject.hasProperty("a16")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a16");
            a16 = new CustomerImage(j);

        }
        if (soapObject.hasProperty("a17")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a17");
            a17 = new CustomerLogin(j);

        }
        if (soapObject.hasProperty("a18")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a18");
            a18 = new CustomerTag(j);

        }
        if (soapObject.hasProperty("a19")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a19");
            a19 = new District(j);

        }
        if (soapObject.hasProperty("a2")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a2");
            a2 = new AccountOperationRequest(j);

        }
        if (soapObject.hasProperty("a20")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a20");
            a20 = new ExternalAccount(j);

        }
        if (soapObject.hasProperty("a21")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a21");
            a21 = new ExternalAccountHistory(j);

        }
        if (soapObject.hasProperty("a22")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a22");
            a22 = new KoloNotification(j);

        }
        if (soapObject.hasProperty("a23")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a23");
            a23 = new GroupImage(j);

        }
        if (soapObject.hasProperty("a24")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a24");
            a24 = new LoginAttempt(j);

        }
        if (soapObject.hasProperty("a25")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a25");
            a25 = new MobileDevice(j);

        }
        if (soapObject.hasProperty("a26")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a26");
            a26 = new Partner(j);

        }
        if (soapObject.hasProperty("a27")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a27");
            a27 = new PartnerAddress(j);

        }
        if (soapObject.hasProperty("a28")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a28");
            a28 = new PartnerBalanceHistory(j);

        }
        if (soapObject.hasProperty("a29")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a29");
            a29 = new Person(j);

        }
        if (soapObject.hasProperty("a3")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a3");
            a3 = new Adresse(j);

        }
        if (soapObject.hasProperty("a30")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a30");
            a30 = new PersonRelationship(j);

        }
        if (soapObject.hasProperty("a31")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a31");
            a31 = new Provision(j);

        }
        if (soapObject.hasProperty("a32")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a32");
            a32 = new RecurringContribution(j);

        }
        if (soapObject.hasProperty("a33")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a33");
            a33 = new RefAddressType(j);

        }
        if (soapObject.hasProperty("a34")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a34");
            a34 = new RefBillStatu(j);

        }
        if (soapObject.hasProperty("a35")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a35");
            a35 = new RefBillType(j);

        }
        if (soapObject.hasProperty("a36")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a36");
            a36 = new RefCustomerType(j);

        }
        if (soapObject.hasProperty("a37")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a37");
            a37 = new RefExternalAccountType(j);

        }
        if (soapObject.hasProperty("a38")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a38");
            a38 = new RefGender(j);

        }
        if (soapObject.hasProperty("a39")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a39");
            a39 = new RefGroupType(j);

        }
        if (soapObject.hasProperty("a4")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a4");
            a4 = new Bill(j);

        }
        if (soapObject.hasProperty("a40")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a40");
            a40 = new RefIndustryCategory(j);

        }
        if (soapObject.hasProperty("a41")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a41");
            a41 = new RefLoginStatu(j);

        }
        if (soapObject.hasProperty("a42")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a42");
            a42 = new RefMaritalStatu(j);

        }
        if (soapObject.hasProperty("a43")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a43");
            a43 = new RefOperationStatu(j);

        }
        if (soapObject.hasProperty("a44")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a44");
            a44 = new RefOperationType(j);

        }
        if (soapObject.hasProperty("a45")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a45");
            a45 = new RefPartnerType(j);

        }
        if (soapObject.hasProperty("a46")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a46");
            a46 = new RefPersonRelationshipType(j);

        }
        if (soapObject.hasProperty("a47")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a47");
            a47 = new RefProvisionStatu(j);

        }
        if (soapObject.hasProperty("a48")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a48");
            a48 = new RefRegistrationStatu(j);

        }
        if (soapObject.hasProperty("a49")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a49");
            a49 = new RefResult(j);

        }
        if (soapObject.hasProperty("a5")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a5");
            a5 = new BillPayment(j);

        }
        if (soapObject.hasProperty("a50")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a50");
            a50 = new RefTransfertStatu(j);

        }
        if (soapObject.hasProperty("a51")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a51");
            a51 = new Registration(j);

        }
        if (soapObject.hasProperty("a52")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a52");
            a52 = new Reseller(j);

        }
        if (soapObject.hasProperty("a53")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a53");
            a53 = new Tag(j);

        }
        if (soapObject.hasProperty("a54")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a54");
            a54 = new Transfert2Cash(j);

        }
        if (soapObject.hasProperty("a55")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a55");
            a55 = new Transfert2CashDetails(j);

        }
        if (soapObject.hasProperty("a56")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a56");
            a56 = new TransfertE2e(j);

        }
        if (soapObject.hasProperty("a57")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a57");
            a57 = new TransfertGroup(j);

        }
        if (soapObject.hasProperty("a58")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a58");
            a58 = new TransfertGroupScheduled(j);

        }
        if (soapObject.hasProperty("a59")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a59");
            a59 = new TransfertP2p(j);

        }
        if (soapObject.hasProperty("a6")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a6");
            a6 = new Business(j);

        }
        if (soapObject.hasProperty("a60")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a60");
            a60 = new TransfertScheduled(j);

        }
        if (soapObject.hasProperty("a61")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a61");
            a61 = new KoloUser(j);

        }
        if (soapObject.hasProperty("a62")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a62");
            a62 = new Wholesaler(j);

        }
        if (soapObject.hasProperty("a7")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a7");
            a7 = new BusinessContact(j);

        }
        if (soapObject.hasProperty("a8")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a8");
            a8 = new City(j);

        }
        if (soapObject.hasProperty("a9")) {
            SoapObject j = (SoapObject) soapObject.getProperty("a9");
            a9 = new Country(j);

        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return a1;
            case 1:
                return a10;
            case 2:
                return a11;
            case 3:
                return a12;
            case 4:
                return a13;
            case 5:
                return a14;
            case 6:
                return a15;
            case 7:
                return a16;
            case 8:
                return a17;
            case 9:
                return a18;
            case 10:
                return a19;
            case 11:
                return a2;
            case 12:
                return a20;
            case 13:
                return a21;
            case 14:
                return a22;
            case 15:
                return a23;
            case 16:
                return a24;
            case 17:
                return a25;
            case 18:
                return a26;
            case 19:
                return a27;
            case 20:
                return a28;
            case 21:
                return a29;
            case 22:
                return a3;
            case 23:
                return a30;
            case 24:
                return a31;
            case 25:
                return a32;
            case 26:
                return a33;
            case 27:
                return a34;
            case 28:
                return a35;
            case 29:
                return a36;
            case 30:
                return a37;
            case 31:
                return a38;
            case 32:
                return a39;
            case 33:
                return a4;
            case 34:
                return a40;
            case 35:
                return a41;
            case 36:
                return a42;
            case 37:
                return a43;
            case 38:
                return a44;
            case 39:
                return a45;
            case 40:
                return a46;
            case 41:
                return a47;
            case 42:
                return a48;
            case 43:
                return a49;
            case 44:
                return a5;
            case 45:
                return a50;
            case 46:
                return a51;
            case 47:
                return a52;
            case 48:
                return a53;
            case 49:
                return a54;
            case 50:
                return a55;
            case 51:
                return a56;
            case 52:
                return a57;
            case 53:
                return a58;
            case 54:
                return a59;
            case 55:
                return a6;
            case 56:
                return a60;
            case 57:
                return a61;
            case 58:
                return a62;
            case 59:
                return a7;
            case 60:
                return a8;
            case 61:
                return a9;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 62;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = AccountOperation.class;
                info.name = "a1";
                break;
            case 1:
                info.type = Currency.class;
                info.name = "a10";
                break;
            case 2:
                info.type = Customer.class;
                info.name = "a11";
                break;
            case 3:
                info.type = CustomerAddress.class;
                info.name = "a12";
                break;
            case 4:
                info.type = CustomerBalanceHistory.class;
                info.name = "a13";
                break;
            case 5:
                info.type = CustomerExternalAccount.class;
                info.name = "a14";
                break;
            case 6:
                info.type = CustomerGroup.class;
                info.name = "a15";
                break;
            case 7:
                info.type = CustomerImage.class;
                info.name = "a16";
                break;
            case 8:
                info.type = CustomerLogin.class;
                info.name = "a17";
                break;
            case 9:
                info.type = CustomerTag.class;
                info.name = "a18";
                break;
            case 10:
                info.type = District.class;
                info.name = "a19";
                break;
            case 11:
                info.type = AccountOperationRequest.class;
                info.name = "a2";
                break;
            case 12:
                info.type = ExternalAccount.class;
                info.name = "a20";
                break;
            case 13:
                info.type = ExternalAccountHistory.class;
                info.name = "a21";
                break;
            case 14:
                info.type = KoloNotification.class;
                info.name = "a22";
                break;
            case 15:
                info.type = GroupImage.class;
                info.name = "a23";
                break;
            case 16:
                info.type = LoginAttempt.class;
                info.name = "a24";
                break;
            case 17:
                info.type = MobileDevice.class;
                info.name = "a25";
                break;
            case 18:
                info.type = Partner.class;
                info.name = "a26";
                break;
            case 19:
                info.type = PartnerAddress.class;
                info.name = "a27";
                break;
            case 20:
                info.type = PartnerBalanceHistory.class;
                info.name = "a28";
                break;
            case 21:
                info.type = Person.class;
                info.name = "a29";
                break;
            case 22:
                info.type = Adresse.class;
                info.name = "a3";
                break;
            case 23:
                info.type = PersonRelationship.class;
                info.name = "a30";
                break;
            case 24:
                info.type = Provision.class;
                info.name = "a31";
                break;
            case 25:
                info.type = RecurringContribution.class;
                info.name = "a32";
                break;
            case 26:
                info.type = RefAddressType.class;
                info.name = "a33";
                break;
            case 27:
                info.type = RefBillStatu.class;
                info.name = "a34";
                break;
            case 28:
                info.type = RefBillType.class;
                info.name = "a35";
                break;
            case 29:
                info.type = RefCustomerType.class;
                info.name = "a36";
                break;
            case 30:
                info.type = RefExternalAccountType.class;
                info.name = "a37";
                break;
            case 31:
                info.type = RefGender.class;
                info.name = "a38";
                break;
            case 32:
                info.type = RefGroupType.class;
                info.name = "a39";
                break;
            case 33:
                info.type = Bill.class;
                info.name = "a4";
                break;
            case 34:
                info.type = RefIndustryCategory.class;
                info.name = "a40";
                break;
            case 35:
                info.type = RefLoginStatu.class;
                info.name = "a41";
                break;
            case 36:
                info.type = RefMaritalStatu.class;
                info.name = "a42";
                break;
            case 37:
                info.type = RefOperationStatu.class;
                info.name = "a43";
                break;
            case 38:
                info.type = RefOperationType.class;
                info.name = "a44";
                break;
            case 39:
                info.type = RefPartnerType.class;
                info.name = "a45";
                break;
            case 40:
                info.type = RefPersonRelationshipType.class;
                info.name = "a46";
                break;
            case 41:
                info.type = RefProvisionStatu.class;
                info.name = "a47";
                break;
            case 42:
                info.type = RefRegistrationStatu.class;
                info.name = "a48";
                break;
            case 43:
                info.type = RefResult.class;
                info.name = "a49";
                break;
            case 44:
                info.type = BillPayment.class;
                info.name = "a5";
                break;
            case 45:
                info.type = RefTransfertStatu.class;
                info.name = "a50";
                break;
            case 46:
                info.type = Registration.class;
                info.name = "a51";
                break;
            case 47:
                info.type = Reseller.class;
                info.name = "a52";
                break;
            case 48:
                info.type = Tag.class;
                info.name = "a53";
                break;
            case 49:
                info.type = Transfert2Cash.class;
                info.name = "a54";
                break;
            case 50:
                info.type = Transfert2CashDetails.class;
                info.name = "a55";
                break;
            case 51:
                info.type = TransfertE2e.class;
                info.name = "a56";
                break;
            case 52:
                info.type = TransfertGroup.class;
                info.name = "a57";
                break;
            case 53:
                info.type = TransfertGroupScheduled.class;
                info.name = "a58";
                break;
            case 54:
                info.type = TransfertP2p.class;
                info.name = "a59";
                break;
            case 55:
                info.type = Business.class;
                info.name = "a6";
                break;
            case 56:
                info.type = TransfertScheduled.class;
                info.name = "a60";
                break;
            case 57:
                info.type = KoloUser.class;
                info.name = "a61";
                break;
            case 58:
                info.type = Wholesaler.class;
                info.name = "a62";
                break;
            case 59:
                info.type = BusinessContact.class;
                info.name = "a7";
                break;
            case 60:
                info.type = City.class;
                info.name = "a8";
                break;
            case 61:
                info.type = Country.class;
                info.name = "a9";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }

    //    @Override
    public void setInnerText(String s) {
    }

}
