package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class Provision implements KvmSerializable {

    private int idProvision;
    private int idProvisionRequest;
    private int idPatnerHistory;
    private int idResellerPartnerAccount;
    private int idWholesalerPartnerAccount;
    private String codeRefProsisionStatus;
    private String provisionDate;
    private int amount;
    private Partner partner;
    private Partner partner1;
    private PartnerBalanceHistory partnerBalanceHistory;
    private RefProvisionStatu refProvisionStatu;

    public Provision() {
    }

    public Provision(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("IdProvision")) {
            Object obj = soapObject.getProperty("IdProvision");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setIdProvision(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setIdProvision((Integer) obj);
            }
        }
        if (soapObject.hasProperty("IdProvisionRequest")) {
            Object obj = soapObject.getProperty("IdProvisionRequest");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setIdProvisionRequest(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setIdProvisionRequest((Integer) obj);
            }
        }
        if (soapObject.hasProperty("IdPatnerHistory")) {
            Object obj = soapObject.getProperty("IdPatnerHistory");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setIdPatnerHistory(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setIdPatnerHistory((Integer) obj);
            }
        }
        if (soapObject.hasProperty("IdResellerPartnerAccount")) {
            Object obj = soapObject.getProperty("IdResellerPartnerAccount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setIdResellerPartnerAccount(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setIdResellerPartnerAccount((Integer) obj);
            }
        }
        if (soapObject.hasProperty("IdWholesalerPartnerAccount")) {
            Object obj = soapObject.getProperty("IdWholesalerPartnerAccount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setIdWholesalerPartnerAccount(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setIdWholesalerPartnerAccount((Integer) obj);
            }
        }
        if (soapObject.hasProperty("CodeRefProsisionStatus")) {
            Object obj = soapObject.getProperty("CodeRefProsisionStatus");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setCodeRefProsisionStatus(j.toString());
            } else if (obj != null && obj instanceof String) {
                setCodeRefProsisionStatus((String) obj);
            }
        }
        if (soapObject.hasProperty("ProvisionDate")) {
            Object obj = soapObject.getProperty("ProvisionDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setProvisionDate(j.toString());
            } else if (obj != null && obj instanceof String) {
                setProvisionDate((String) obj);
            }
        }
        if (soapObject.hasProperty("Amount")) {
            Object obj = soapObject.getProperty("Amount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                setAmount(Integer.parseInt(j.toString()));
            } else if (obj != null && obj instanceof Number) {
                setAmount((Integer) obj);
            }
        }
        if (soapObject.hasProperty("Partner")) {
            SoapObject j = (SoapObject) soapObject.getProperty("Partner");
            setPartner(new Partner(j));

        }
        if (soapObject.hasProperty("Partner1")) {
            SoapObject j = (SoapObject) soapObject.getProperty("Partner1");
            setPartner1(new Partner(j));

        }
        if (soapObject.hasProperty("PartnerBalanceHistory")) {
            SoapObject j = (SoapObject) soapObject.getProperty("PartnerBalanceHistory");
            setPartnerBalanceHistory(new PartnerBalanceHistory(j));

        }
        if (soapObject.hasProperty("RefProvisionStatu")) {
            SoapObject j = (SoapObject) soapObject.getProperty("RefProvisionStatu");
            setRefProvisionStatu(new RefProvisionStatu(j));

        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return getIdProvision();
            case 1:
                return getIdProvisionRequest();
            case 2:
                return getIdPatnerHistory();
            case 3:
                return getIdResellerPartnerAccount();
            case 4:
                return getIdWholesalerPartnerAccount();
            case 5:
                return getCodeRefProsisionStatus();
            case 6:
                return getProvisionDate();
            case 7:
                return getAmount();
            case 8:
                return getPartner();
            case 9:
                return getPartner1();
            case 10:
                return getPartnerBalanceHistory();
            case 11:
                return getRefProvisionStatu();
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdProvision";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdProvisionRequest";
                break;
            case 2:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdPatnerHistory";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdResellerPartnerAccount";
                break;
            case 4:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdWholesalerPartnerAccount";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CodeRefProsisionStatus";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ProvisionDate";
                break;
            case 7:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Amount";
                break;
            case 8:
                info.type = Partner.class;
                info.name = "Partner";
                break;
            case 9:
                info.type = Partner.class;
                info.name = "Partner1";
                break;
            case 10:
                info.type = PartnerBalanceHistory.class;
                info.name = "PartnerBalanceHistory";
                break;
            case 11:
                info.type = RefProvisionStatu.class;
                info.name = "RefProvisionStatu";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }

    //    @Override
    public void setInnerText(String s) {
    }

    public int getIdProvision() {
        return idProvision;
    }

    public void setIdProvision(int idProvision) {
        this.idProvision = idProvision;
    }

    public int getIdProvisionRequest() {
        return idProvisionRequest;
    }

    public void setIdProvisionRequest(int idProvisionRequest) {
        this.idProvisionRequest = idProvisionRequest;
    }

    public int getIdPatnerHistory() {
        return idPatnerHistory;
    }

    public void setIdPatnerHistory(int idPatnerHistory) {
        this.idPatnerHistory = idPatnerHistory;
    }

    public int getIdResellerPartnerAccount() {
        return idResellerPartnerAccount;
    }

    public void setIdResellerPartnerAccount(int idResellerPartnerAccount) {
        this.idResellerPartnerAccount = idResellerPartnerAccount;
    }

    public int getIdWholesalerPartnerAccount() {
        return idWholesalerPartnerAccount;
    }

    public void setIdWholesalerPartnerAccount(int idWholesalerPartnerAccount) {
        this.idWholesalerPartnerAccount = idWholesalerPartnerAccount;
    }

    public String getCodeRefProsisionStatus() {
        return codeRefProsisionStatus;
    }

    public void setCodeRefProsisionStatus(String codeRefProsisionStatus) {
        this.codeRefProsisionStatus = codeRefProsisionStatus;
    }

    public String getProvisionDate() {
        return provisionDate;
    }

    public void setProvisionDate(String provisionDate) {
        this.provisionDate = provisionDate;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public Partner getPartner() {
        return partner;
    }

    public void setPartner(Partner partner) {
        this.partner = partner;
    }

    public Partner getPartner1() {
        return partner1;
    }

    public void setPartner1(Partner partner1) {
        this.partner1 = partner1;
    }

    public PartnerBalanceHistory getPartnerBalanceHistory() {
        return partnerBalanceHistory;
    }

    public void setPartnerBalanceHistory(PartnerBalanceHistory partnerBalanceHistory) {
        this.partnerBalanceHistory = partnerBalanceHistory;
    }

    public RefProvisionStatu getRefProvisionStatu() {
        return refProvisionStatu;
    }

    public void setRefProvisionStatu(RefProvisionStatu refProvisionStatu) {
        this.refProvisionStatu = refProvisionStatu;
    }
}
