package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class RefCustomerType implements KvmSerializable {
	
	private String customerTypeCode;
	private String customerTypeDescription;
	
	public RefCustomerType() {
	}
	
	public RefCustomerType(SoapObject soapObject) {
		if (soapObject == null)
			return;
		if (soapObject.hasProperty("CustomerTypeCode")) {
			Object obj = soapObject.getProperty("CustomerTypeCode");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setCustomerTypeCode(j.toString());
			} else if (obj != null && obj instanceof String) {
				setCustomerTypeCode((String) obj);
			}
		}
		if (soapObject.hasProperty("CustomerTypeDescription")) {
			Object obj = soapObject.getProperty("CustomerTypeDescription");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
				SoapPrimitive j = (SoapPrimitive) obj;
				setCustomerTypeDescription(j.toString());
			} else if (obj != null && obj instanceof String) {
				setCustomerTypeDescription((String) obj);
			}
		}
	}
	
	@Override
	public Object getProperty(int arg0) {
		switch (arg0) {
			case 0:
				return getCustomerTypeCode();
			case 1:
				return getCustomerTypeDescription();
		}
		return null;
	}
	
	@Override
	public int getPropertyCount() {
		return 2;
	}
	
	@Override
	public void setProperty(int arg0, Object arg1) {
	}
	
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		switch (index) {
			case 0:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "CustomerTypeCode";
				break;
			case 1:
				info.type = PropertyInfo.STRING_CLASS;
				info.name = "CustomerTypeDescription";
				break;
		}
	}
	
	public String getCustomerTypeCode() {
		return customerTypeCode;
	}
	
	public void setCustomerTypeCode(String customerTypeCode) {
		this.customerTypeCode = customerTypeCode;
	}
	
	public String getCustomerTypeDescription() {
		return customerTypeDescription;
	}
	
	public void setCustomerTypeDescription(String customerTypeDescription) {
		this.customerTypeDescription = customerTypeDescription;
	}
	
	//    @Override
	public String getInnerText() {
		return null;
	}
	
	//    @Override
	public void setInnerText(String s) {
	}
}
