package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RefMaritalStatu extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String MaritalStatusCode;
    
    private String MaritalStatusDescription;
    
    private ArrayOfPerson People;
    
    public String getMaritalStatusCode()
    {
        return this.MaritalStatusCode;
    }
    
    public void setMaritalStatusCode(String value)
    {
        this.MaritalStatusCode = value;     
    }
    
    public String getMaritalStatusDescription()
    {
        return this.MaritalStatusDescription;
    }
    
    public void setMaritalStatusDescription(String value)
    {
        this.MaritalStatusDescription = value;     
    }
    
    public ArrayOfPerson getPeople()
    {
        return this.People;
    }
    
    public void setPeople(ArrayOfPerson value)
    {
        this.People = value;     
    }


    public RefMaritalStatu(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("MaritalStatusCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaritalStatusCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MaritalStatusCode = (String)obj;
                }
                else{
                    this.MaritalStatusCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("MaritalStatusDescription"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.MaritalStatusDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.MaritalStatusDescription = (String)obj;
                }
                else{
                    this.MaritalStatusDescription = "";
                }
            }
            return true;
        }
        if (info.name.equals("People"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.People = (ArrayOfPerson)__envelope.get(j,ArrayOfPerson.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.MaritalStatusCode!=null?this.MaritalStatusCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.MaritalStatusDescription!=null?this.MaritalStatusDescription:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.People!=null?this.People:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MaritalStatusCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MaritalStatusDescription";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "People";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
