package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RefOperationType extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String OperationTypeCode;
    
    private String OperationTypeName;
    
    private ArrayOfAccountOperation AccountOperations;
    
    private ArrayOfAccountOperationRequest AccountOperationRequests;
    
    private ArrayOfCustomerBalanceHistory CustomerBalanceHistories;
    
    private ArrayOfTransfertE2e TransfertE2e;
    
    public String getOperationTypeCode()
    {
        return this.OperationTypeCode;
    }
    
    public void setOperationTypeCode(String value)
    {
        this.OperationTypeCode = value;     
    }
    
    public String getOperationTypeName()
    {
        return this.OperationTypeName;
    }
    
    public void setOperationTypeName(String value)
    {
        this.OperationTypeName = value;     
    }
    
    public ArrayOfAccountOperation getAccountOperations()
    {
        return this.AccountOperations;
    }
    
    public void setAccountOperations(ArrayOfAccountOperation value)
    {
        this.AccountOperations = value;     
    }
    
    public ArrayOfAccountOperationRequest getAccountOperationRequests()
    {
        return this.AccountOperationRequests;
    }
    
    public void setAccountOperationRequests(ArrayOfAccountOperationRequest value)
    {
        this.AccountOperationRequests = value;     
    }
    
    public ArrayOfCustomerBalanceHistory getCustomerBalanceHistories()
    {
        return this.CustomerBalanceHistories;
    }
    
    public void setCustomerBalanceHistories(ArrayOfCustomerBalanceHistory value)
    {
        this.CustomerBalanceHistories = value;     
    }
    
    public ArrayOfTransfertE2e getTransfertE2e()
    {
        return this.TransfertE2e;
    }
    
    public void setTransfertE2e(ArrayOfTransfertE2e value)
    {
        this.TransfertE2e = value;     
    }


    public RefOperationType(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("OperationTypeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OperationTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.OperationTypeCode = (String)obj;
                }
                else{
                    this.OperationTypeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("OperationTypeName"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.OperationTypeName = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.OperationTypeName = (String)obj;
                }
                else{
                    this.OperationTypeName = "";
                }
            }
            return true;
        }
        if (info.name.equals("AccountOperations"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AccountOperations = (ArrayOfAccountOperation)__envelope.get(j,ArrayOfAccountOperation.class,false);
            }
            return true;
        }
        if (info.name.equals("AccountOperationRequests"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.AccountOperationRequests = (ArrayOfAccountOperationRequest)__envelope.get(j,ArrayOfAccountOperationRequest.class,false);
            }
            return true;
        }
        if (info.name.equals("CustomerBalanceHistories"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.CustomerBalanceHistories = (ArrayOfCustomerBalanceHistory)__envelope.get(j,ArrayOfCustomerBalanceHistory.class,false);
            }
            return true;
        }
        if (info.name.equals("TransfertE2e"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.TransfertE2e = (ArrayOfTransfertE2e)__envelope.get(j,ArrayOfTransfertE2e.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.OperationTypeCode!=null?this.OperationTypeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.OperationTypeName!=null?this.OperationTypeName:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.AccountOperations!=null?this.AccountOperations:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==3)
        {
            return this.AccountOperationRequests!=null?this.AccountOperationRequests:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==4)
        {
            return this.CustomerBalanceHistories!=null?this.CustomerBalanceHistories:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.TransfertE2e!=null?this.TransfertE2e:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OperationTypeCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "OperationTypeName";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "AccountOperations";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "AccountOperationRequests";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "CustomerBalanceHistories";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "TransfertE2e";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
