package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RefPersonRelationshipType extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String RelationshipTypeCode;
    
    private String RelationshipTypeDescription;
    
    private ArrayOfPersonRelationship PersonRelationships;
    
    public String getRelationshipTypeCode()
    {
        return this.RelationshipTypeCode;
    }
    
    public void setRelationshipTypeCode(String value)
    {
        this.RelationshipTypeCode = value;     
    }
    
    public String getRelationshipTypeDescription()
    {
        return this.RelationshipTypeDescription;
    }
    
    public void setRelationshipTypeDescription(String value)
    {
        this.RelationshipTypeDescription = value;     
    }
    
    public ArrayOfPersonRelationship getPersonRelationships()
    {
        return this.PersonRelationships;
    }
    
    public void setPersonRelationships(ArrayOfPersonRelationship value)
    {
        this.PersonRelationships = value;     
    }


    public RefPersonRelationshipType(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("RelationshipTypeCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RelationshipTypeCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RelationshipTypeCode = (String)obj;
                }
                else{
                    this.RelationshipTypeCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("RelationshipTypeDescription"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.RelationshipTypeDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.RelationshipTypeDescription = (String)obj;
                }
                else{
                    this.RelationshipTypeDescription = "";
                }
            }
            return true;
        }
        if (info.name.equals("PersonRelationships"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.PersonRelationships = (ArrayOfPersonRelationship)__envelope.get(j,ArrayOfPersonRelationship.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.RelationshipTypeCode!=null?this.RelationshipTypeCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.RelationshipTypeDescription!=null?this.RelationshipTypeDescription:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.PersonRelationships!=null?this.PersonRelationships:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RelationshipTypeCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RelationshipTypeDescription";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "PersonRelationships";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
