package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RefResult extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private String ResultCode;
    
    private String ResultDescription;
    
    private ArrayOfLoginAttempt LoginAttempts;
    
    public String getResultCode()
    {
        return this.ResultCode;
    }
    
    public void setResultCode(String value)
    {
        this.ResultCode = value;     
    }
    
    public String getResultDescription()
    {
        return this.ResultDescription;
    }
    
    public void setResultDescription(String value)
    {
        this.ResultDescription = value;     
    }
    
    public ArrayOfLoginAttempt getLoginAttempts()
    {
        return this.LoginAttempts;
    }
    
    public void setLoginAttempts(ArrayOfLoginAttempt value)
    {
        this.LoginAttempts = value;     
    }


    public RefResult(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }
    
    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("ResultCode"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ResultCode = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ResultCode = (String)obj;
                }
                else{
                    this.ResultCode = "";
                }
            }
            return true;
        }
        if (info.name.equals("ResultDescription"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.ResultDescription = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.ResultDescription = (String)obj;
                }
                else{
                    this.ResultDescription = "";
                }
            }
            return true;
        }
        if (info.name.equals("LoginAttempts"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.LoginAttempts = (ArrayOfLoginAttempt)__envelope.get(j,ArrayOfLoginAttempt.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.ResultCode!=null?this.ResultCode:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==1)
        {
            return this.ResultDescription!=null?this.ResultDescription:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==2)
        {
            return this.LoginAttempts!=null?this.LoginAttempts:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ResultCode";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ResultDescription";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "LoginAttempts";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
