package fr.cyberix.kolo.model.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class RefTransfertStatu implements KvmSerializable {

    public String transfertStatusCode;
    public String transfertStatusDescription;

    public RefTransfertStatu() {
    }

    public RefTransfertStatu(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("TransfertStatusCode")) {
            Object obj = soapObject.getProperty("TransfertStatusCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                transfertStatusCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                transfertStatusCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("TransfertStatusDescription")) {
            Object obj = soapObject.getProperty("TransfertStatusDescription");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                transfertStatusDescription = j.toString();
            } else if (obj != null && obj instanceof String) {
                transfertStatusDescription = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return transfertStatusCode;
            case 1:
                return transfertStatusDescription;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TransfertStatusCode";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TransfertStatusDescription";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }

    //    @Override
    public void setInnerText(String s) {
    }

}
