package fr.cyberix.kolo.model.entities;
//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.10.3.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class WholeSalerHistory extends AttributeContainer implements KvmSerializable
{

    
    private transient java.lang.Object __source;    
    
    private Integer IdWholeSalerHistory=0;
    
    private Integer IdWholeSalerUser=0;
    
    private Integer IdProvision;
    
    private String DateCreation;
    
    private String Description;
    
    private Integer IdPartner=0;
    
    private Partner Partner;
    
    private Provision Provision;
    
    private WholeSalerUser WholeSalerUser;
    
    public Integer getIdWholeSalerHistory()
    {
        return this.IdWholeSalerHistory;
    }
    
    public void setIdWholeSalerHistory(Integer value)
    {
        this.IdWholeSalerHistory = value;     
    }
    
    public Integer getIdWholeSalerUser()
    {
        return this.IdWholeSalerUser;
    }
    
    public void setIdWholeSalerUser(Integer value)
    {
        this.IdWholeSalerUser = value;     
    }
    
    public Integer getIdProvision()
    {
        return this.IdProvision;
    }
    
    public void setIdProvision(Integer value)
    {
        this.IdProvision = value;     
    }
    
    public String getDateCreation()
    {
        return this.DateCreation;
    }
    
    public void setDateCreation(String value)
    {
        this.DateCreation = value;     
    }
    
    public String getDescription()
    {
        return this.Description;
    }
    
    public void setDescription(String value)
    {
        this.Description = value;     
    }
    
    public Integer getIdPartner()
    {
        return this.IdPartner;
    }
    
    public void setIdPartner(Integer value)
    {
        this.IdPartner = value;     
    }
    
    public Partner getPartner()
    {
        return this.Partner;
    }
    
    public void setPartner(Partner value)
    {
        this.Partner = value;     
    }
    
    public Provision getProvision()
    {
        return this.Provision;
    }
    
    public void setProvision(Provision value)
    {
        this.Provision = value;     
    }
    
    public WholeSalerUser getWholeSalerUser()
    {
        return this.WholeSalerUser;
    }
    
    public void setWholeSalerUser(WholeSalerUser value)
    {
        this.WholeSalerUser = value;     
    }



    public WholeSalerHistory(SoapObject j){
        loadFromSoap(j, new ExtendedSoapSerializationEnvelope());
    }

    public void loadFromSoap(java.lang.Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }



    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,ExtendedSoapSerializationEnvelope __envelope)
    {
        java.lang.Object obj = info.getValue();
        if (info.name.equals("IdWholeSalerHistory"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdWholeSalerHistory = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdWholeSalerHistory = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdWholeSalerUser"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdWholeSalerUser = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdWholeSalerUser = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("IdProvision"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdProvision = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdProvision = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("DateCreation"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.DateCreation = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.DateCreation = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Description"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.Description = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.Description = (String)obj;
                }
                else{
                    this.Description = "";
                }
            }
            return true;
        }
        if (info.name.equals("IdPartner"))
        {
            if(obj!=null)
            {
                if (obj instanceof SoapPrimitive)
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.IdPartner = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.IdPartner = (Integer)obj;
                }
            }
            return true;
        }
        if (info.name.equals("Partner"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Partner = (Partner)__envelope.get(j,Partner.class,false);
            }
            return true;
        }
        if (info.name.equals("Provision"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.Provision = (Provision)__envelope.get(j,Provision.class,false);
            }
            return true;
        }
        if (info.name.equals("WholeSalerUser"))
        {
            if(obj!=null)
            {
                java.lang.Object j = obj;
                this.WholeSalerUser = (WholeSalerUser)__envelope.get(j,WholeSalerUser.class,false);
            }
            return true;
        }
        return false;
    }
    
    public java.lang.Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.IdWholeSalerHistory;
        }
        else if(propertyIndex==1)
        {
            return this.IdWholeSalerUser;
        }
        else if(propertyIndex==2)
        {
            return this.IdProvision!=null?this.IdProvision:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==3)
        {
            return this.DateCreation!=null?this.DateCreation:SoapPrimitive.NullNilElement;
        }
        else if(propertyIndex==4)
        {
            return this.Description!=null?this.Description:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==5)
        {
            return this.IdPartner;
        }
        else if(propertyIndex==6)
        {
            return this.Partner!=null?this.Partner:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==7)
        {
            return this.Provision!=null?this.Provision:SoapPrimitive.NullSkip;
        }
        else if(propertyIndex==8)
        {
            return this.WholeSalerUser!=null?this.WholeSalerUser:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 9;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdWholeSalerHistory";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdWholeSalerUser";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdProvision";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateCreation";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Description";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdPartner";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==6)
        {
            info.type = Partner.class;
            info.name = "Partner";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==7)
        {
            info.type = Provision.class;
            info.name = "Provision";
            info.namespace= "http://kolo.cyberix.fr/";
        }
        else if(propertyIndex==8)
        {
            info.type = WholeSalerUser.class;
            info.name = "WholeSalerUser";
            info.namespace= "http://kolo.cyberix.fr/";
        }
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}
