package fr.cyberix.kolo.entities;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/1/2018 1:24:28 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class AccountOperationRequest implements KvmSerializable {

    public int idAccountOperationRequest;
    public int idCustomerAccount;
    public String requestDate;
    public String operationTypeCode;
    public String operationStatusCode;
    public int amount;
    public AccountOperation accountOperation;
    public RefOperationStatu refOperationStatu;
    public RefOperationType refOperationType;
    public Customer customer;

    public AccountOperationRequest() {
    }

    public AccountOperationRequest(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("IdAccountOperationRequest")) {
            Object obj = soapObject.getProperty("IdAccountOperationRequest");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                idAccountOperationRequest = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                idAccountOperationRequest = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("IdCustomerAccount")) {
            Object obj = soapObject.getProperty("IdCustomerAccount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                idCustomerAccount = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                idCustomerAccount = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("RequestDate")) {
            Object obj = soapObject.getProperty("RequestDate");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                requestDate = j.toString();
            } else if (obj != null && obj instanceof String) {
                requestDate = (String) obj;
            }
        }
        if (soapObject.hasProperty("OperationTypeCode")) {
            Object obj = soapObject.getProperty("OperationTypeCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                operationTypeCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                operationTypeCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("OperationStatusCode")) {
            Object obj = soapObject.getProperty("OperationStatusCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                operationStatusCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                operationStatusCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("Amount")) {
            Object obj = soapObject.getProperty("Amount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                amount = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                amount = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("AccountOperation")) {
            SoapObject j = (SoapObject) soapObject.getProperty("AccountOperation");
            accountOperation = new AccountOperation(j);

        }
        if (soapObject.hasProperty("RefOperationStatu")) {
            SoapObject j = (SoapObject) soapObject.getProperty("RefOperationStatu");
            refOperationStatu = new RefOperationStatu(j);

        }
        if (soapObject.hasProperty("RefOperationType")) {
            SoapObject j = (SoapObject) soapObject.getProperty("RefOperationType");
            refOperationType = new RefOperationType(j);

        }
        if (soapObject.hasProperty("Customer")) {
            SoapObject j = (SoapObject) soapObject.getProperty("Customer");
            customer = new Customer(j);

        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return idAccountOperationRequest;
            case 1:
                return idCustomerAccount;
            case 2:
                return requestDate;
            case 3:
                return operationTypeCode;
            case 4:
                return operationStatusCode;
            case 5:
                return amount;
            case 6:
                return accountOperation;
            case 7:
                return refOperationStatu;
            case 8:
                return refOperationType;
            case 9:
                return customer;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdAccountOperationRequest";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "IdCustomerAccount";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "RequestDate";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OperationTypeCode";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "OperationStatusCode";
                break;
            case 5:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "Amount";
                break;
            case 6:
                info.type = AccountOperation.class;
                info.name = "AccountOperation";
                break;
            case 7:
                info.type = RefOperationStatu.class;
                info.name = "RefOperationStatu";
                break;
            case 8:
                info.type = RefOperationType.class;
                info.name = "RefOperationType";
                break;
            case 9:
                info.type = Customer.class;
                info.name = "Customer";
                break;
        }
    }

    //    @Override
    public String getInnerText() {
        return null;
    }

    //    @Override
    public void setInnerText(String s) {
    }

}
